### ISSUE TITLE
Open with GIMP/Inkscape (probably others) causes flatpak to crash 

### ISSUE THREAD

**Issue by ahayzen** [flatpak/flatpak#1428]
I tried to open an svg in Inkscape or a png in GIMP from nautilus, this used to work before (maybe 0.11.1 has broken something), but now is crashing flatpak.

Syslog when launching Inkscape
```
Feb 18 21:10:46 andrew-XPS-13-9360 systemd[16385]: flatpak-org.inkscape.Inkscape-10638.scope: Failed to add PIDs to scope's control group: Permission denied
Feb 18 21:10:46 andrew-XPS-13-9360 systemd[16385]: Failed to start flatpak-org.inkscape.Inkscape-10638.scope.
Feb 18 21:10:46 andrew-XPS-13-9360 systemd[16385]: flatpak-org.inkscape.Inkscape-10638.scope: Unit entered failed state.
Feb 18 21:10:46 andrew-XPS-13-9360 kernel: flatpak[10638]: segfault at 0 ip 000055ce799258f9 sp 00007ffdf773c7a0 error 4 in flatpak[55ce798c3000+a4000]
```

Syslog when launching GIMP
```
Feb 18 21:11:40 andrew-XPS-13-9360 systemd[16385]: flatpak-org.gimp.GIMP-11286.scope: Failed to add PIDs to scope's control group: Permission denied
Feb 18 21:11:40 andrew-XPS-13-9360 systemd[16385]: Failed to start flatpak-org.gimp.GIMP-11286.scope.
Feb 18 21:11:40 andrew-XPS-13-9360 systemd[16385]: flatpak-org.gimp.GIMP-11286.scope: Unit entered failed state.
Feb 18 21:11:40 andrew-XPS-13-9360 kernel: flatpak[11286]: segfault at 0 ip 00005590dc93c8f9 sp 00007fff40b7c080 error 4 in flatpak[5590dc8da000+a4000]
```

Some parts of the apport trace when the flatpak process crashes, https://pastebin.ubuntu.com/p/ThKxG2Q7m9/ let me know if you want the whole crash file.

```
$ apt-cache policy flatpak
flatpak:
  Installed: 0.11.1-0alexlarsson1~artful
  Candidate: 0.11.1-0alexlarsson1~artful
  Version table:
 *** 0.11.1-0alexlarsson1~artful 500
        500 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu artful/main amd64 Packages
        100 /var/lib/dpkg/status
     0.8.7-5 500
        500 http://gb.archive.ubuntu.com/ubuntu artful/universe amd64 Packages
$ apt-cache policy xdg-desktop-portal
xdg-desktop-portal:
  Installed: 0.10-0alexlarsson2~artful
  Candidate: 0.10-0alexlarsson2~artful
  Version table:
 *** 0.10-0alexlarsson2~artful 500
        500 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu artful/main amd64 Packages
        100 /var/lib/dpkg/status
     0.8-2 500
        500 http://gb.archive.ubuntu.com/ubuntu artful/universe amd64 Packages
$ apt-cache policy xdg-desktop-portal-gtk
xdg-desktop-portal-gtk:
  Installed: 0.10-0alexlarsson1~artful
  Candidate: 0.10-0alexlarsson1~artful
  Version table:
 *** 0.10-0alexlarsson1~artful 500
        500 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu artful/main amd64 Packages
        100 /var/lib/dpkg/status
     0.7-2 500
        500 http://gb.archive.ubuntu.com/ubuntu artful/universe amd64 Packages
```

**Comment by mwleeds** [comment]
FWIW I just saw a similar crash trying to open a file with VLC

**Comment by mwleeds** [comment]
```
#0  0x00000000004675b4 in flatpak_exports_path_get_mode (exports=0x0, path=0xea7540 "/run/media/mwleeds/b5a5b6a8-c00a-49a1-bf3c-3889a436c8b5/movie.mkv") at common/flatpak-exports.c:293
#1  0x00000000004678b1 in flatpak_exports_path_is_visible (exports=0x0, path=0xea7540 "/run/media/mwleeds/b5a5b6a8-c00a-49a1-bf3c-3889a436c8b5/movie.mkv") at common/flatpak-exports.c:357
#2  0x00000000004603f3 in add_rest_args (app_id=0xe8c350 "org.videolan.VLC", exports=0x0, file_forwarding=1, doc_mount_path=0xea37b0 "/run/user/1000/doc", argv_array=0xe97ec0, args=0x7fff9ccedf48, n_args=4, error=0x7fff9ccedd98) at common/flatpak-run.c:2511
#3  0x0000000000461b71 in flatpak_run_app (app_ref=0xe83090 "app/org.videolan.VLC/x86_64/stable", app_deploy=0xe60f20, extra_context=0xe60ed0, custom_runtime=0x0, custom_runtime_version=0x0, flags=FLATPAK_RUN_FLAG_FILE_FORWARDING, custom_command=0xe83010 "/app/bin/vlc", args=0x7fff9ccedf48, n_args=4, cancellable=0x0, error=0x7fff9ccedd98) at common/flatpak-run.c:3008
#4  0x0000000000423907 in flatpak_builtin_run (argc=1, argv=0x7fff9ccedf18, cancellable=0x0, error=0x7fff9ccedd98) at app/flatpak-builtins-run.c:173
#5  0x0000000000413d18 in flatpak_run (argc=10, argv=0x7fff9ccedf18, res_error=0x7fff9ccede00) at app/flatpak-main.c:512
#6  0x0000000000414052 in main (argc=11, argv=0x7fff9ccedf18) at app/flatpak-main.c:606
```

I thought this was caused by using the latest flatpak from master without the latest `xdg-desktop-portal`/`xdg-desktop-portal-gtk`, but then I built and installed both of those and the issue persists.

**Comment by ahayzen** [comment]
FWIW, this also happens on 0.11.2.
