### ISSUE TITLE
Flatpak update segfaults

### ISSUE THREAD

**Issue by bochecha** [flatpak/flatpak#1580]
## Linux distribution and version

Fedora 28.

## Flatpak version

flatpak-0.11.3-1.fc28.x86_64

## Description of the problem

When I run `flatpak update`, Flatpak segfaults on my test repo:

```
$ flatpak update 
Looking for updates...
Updating appstream data for remote local-dino

(flatpak update:9497): GLib-CRITICAL **: 11:42:14.490: g_bytes_get_size: assertion 'bytes != NULL' failed

(flatpak update:9497): GLib-CRITICAL **: 11:42:14.490: g_bytes_get_data: assertion 'bytes != NULL' failed

(flatpak update:9497): GLib-GIO-CRITICAL **: 11:42:14.490: g_file_replace_contents: assertion 'contents != NULL' failed
Segmentation fault (core dumped)
```

There might be something wrong with that repo (I'm not sure what, though, but I'm interested in knowing what it is as that's for a Flatpak I'm working on and eventually intend to submit upstream), but I guess Flatpak should probably fail more gracefully?

## Steps to reproduce

```
$ git clone https://github.com/bochecha/dino.git
$ cd dino
$ git checkout flatpak
$ flatpak-builder --force-clean --ccache --repo=repo app im.dino.Dino.json
$ flatpak build-update-repo --prune --prune-depth=4 --generate-static-deltas repo
$ flatpak remote-add --no-gpg-verify local-dino repo
$ flatpak remote-ls local-dino
Ref         
im.dino.Dino
```

At this point:

```
$ flatpak update
Looking for updates...
Updating appstream data for remote local-dino

(flatpak update:18227): GLib-CRITICAL **: 11:49:01.905: g_bytes_get_size: assertion 'bytes != NULL' failed

(flatpak update:18227): GLib-CRITICAL **: 11:49:01.905: g_bytes_get_data: assertion 'bytes != NULL' failed

(flatpak update:18227): GLib-GIO-CRITICAL **: 11:49:01.905: g_file_replace_contents: assertion 'contents != NULL' failed
Segmentation fault (core dumped)
```

**Comment by bochecha** [comment]
Here is the backtrace:

```
(gdb) t a a bt

Thread 5 (Thread 0x7fffdacec700 (LWP 4361)):
#0  0x00007ffff54b2929 in __GI___poll (fds=0x7fffd4019fe0, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff6293b16 in g_main_context_poll (priority=<optimized out>, n_fds=3, fds=0x7fffd4019fe0, timeout=<optimized out>, context=0x7fffd4018470) at gmain.c:4204
#2  0x00007ffff6293b16 in g_main_context_iterate (context=0x7fffd4018470, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3898
#3  0x00007ffff6293ed2 in g_main_loop_run (loop=0x7fffd40185b0) at gmain.c:4099
#4  0x00007ffff688366a in gdbus_shared_thread_func (user_data=0x7fffd4018440) at gdbusprivate.c:275
#5  0x00007ffff62bbcda in g_thread_proxy (data=0x55555589b2d0) at gthread.c:784
#6  0x00007ffff5789564 in start_thread (arg=<optimized out>) at pthread_create.c:463
#7  0x00007ffff54bd31f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7fffdbfff700 (LWP 4360)):
#0  0x00007ffff54b2929 in __GI___poll (fds=0x555555952bc0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff6293b16 in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x555555952bc0, timeout=<optimized out>, context=0x555555952a80) at gmain.c:4204
#2  0x00007ffff6293b16 in g_main_context_iterate (context=context@entry=0x555555952a80, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3898
#3  0x00007ffff6293c40 in g_main_context_iteration (context=context@entry=0x555555952a80, may_block=may_block@entry=1) at gmain.c:3964
#4  0x00007fffdb1efe4d in dconf_gdbus_worker_thread (user_data=0x555555952a80) at ../gdbus/dconf-gdbus-thread.c:82
#5  0x00007ffff62bbcda in g_thread_proxy (data=0x55555589ab70) at gthread.c:784
#6  0x00007ffff5789564 in start_thread (arg=<optimized out>) at pthread_create.c:463
#7  0x00007ffff54bd31f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fffe0bd8700 (LWP 4344)):
#0  0x00007ffff54b2929 in __GI___poll (fds=0x55555589b810, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff6293b16 in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x55555589b810, timeout=<optimized out>, context=0x55555589a4d0) at gmain.c:4204
#2  0x00007ffff6293b16 in g_main_context_iterate (context=context@entry=0x55555589a4d0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3898
#3  0x00007ffff6293c40 in g_main_context_iteration (context=0x55555589a4d0, may_block=may_block@entry=1) at gmain.c:3964
#4  0x00007ffff6293c91 in glib_worker_main (data=<optimized out>) at gmain.c:5773
#5  0x00007ffff62bbcda in g_thread_proxy (data=0x55555589a800) at gthread.c:784
#6  0x00007ffff5789564 in start_thread (arg=<optimized out>) at pthread_create.c:463
#7  0x00007ffff54bd31f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffff7fb9300 (LWP 4340)):
#0  0x000055555558b158 in update_appstream (dirs=0x555555851400, remote=<optimized out>, arch=0x55555560acf6 "x86_64", ttl=0, quiet=0, cancellable=0x0, error=<optimized out>) at app/flatpak-builtins-utils.c:493
#1  0x0000555555594ccf in flatpak_builtin_update (argc=<optimized out>, argv=<optimized out>, cancellable=0x0, error=0x7fffffffde78) at app/flatpak-builtins-update.c:232
#2  0x000055555558930f in flatpak_run (res_error=0x7fffffffde60, argv=<optimized out>, argc=<optimized out>) at app/flatpak-main.c:512
#3  0x000055555558930f in main (argc=<optimized out>, argv=<optimized out>) at app/flatpak-main.c:602
#4  0x00007ffff53e61bb in __libc_start_main (main=0x555555589180 <main>, argc=2, argv=0x7fffffffdfa8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdf98) at ../csu/libc-start.c:308
#5  0x000055555558978a in _start () at app/flatpak-main.c:565
```

**Comment by alexlarsson** [comment]
With master i instead get:
```
$ flatpak update --appstream local-dino
error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error pulling from repo: Can't pull from untrusted non-gpg verified remote
```

Which is better than a crash, but I think it should actually work, as the remote its local.
