### ISSUE TITLE
flatpak build-export --gpg-sign crashes when two keys with the same UID exist

### ISSUE THREAD

**Issue by muelli** [flatpak/flatpak#1655]
## Flatpak version
Flatpak 0.11.6

## Description of the problem
` /usr/bin/flatpak build-export --arch=x86_64 --gpg-sign=tobiasmue@gnome.org --exclude=/lib/debug/\* --include=/lib/debug/app --exclude=/share/runtime/locale/\*/\* /var/tmp/fb.repo fpbuilder master**`
crashes:

```
Thread 1 "flatpak" received signal SIGSEGV, Segmentation fault.
0x00007ffff583a138 in malloc_consolidate (
    av=av@entry=0x7ffff5b8bc20 <main_arena>) at malloc.c:4498
4498	malloc.c: No such file or directory.
(gdb) bt
#0  0x00007ffff583a138 in malloc_consolidate (av=av@entry=0x7ffff5b8bc20 <main_arena>) at malloc.c:4498
#1  0x00007ffff583cf16 in _int_malloc (av=av@entry=0x7ffff5b8bc20 <main_arena>, bytes=bytes@entry=32816) at malloc.c:3706
#2  0x00007ffff583ff3e in __GI___libc_malloc (bytes=32816) at malloc.c:3086
#3  0x00007ffff5884f6c in __alloc_dir (fd=fd@entry=12, close_fd=close_fd@entry=false, flags=<optimised out>, statp=statp@entry=0x7fffffffd560)
    at ../sysdeps/posix/opendir.c:218
#4  0x00007ffff588563c in __fdopendir (fd=12)
    at ../sysdeps/posix/fdopendir.c:50
#5  0x00007ffff72e6de2 in glnx_dirfd_iterator_init_take_fd (dfd=0x7fffffffd684, dfd_iter=0x7fffffffd700, error=0x0) at libglnx/glnx-dirfd.c:127
#6  0x00007ffff72e6d80 in glnx_dirfd_iterator_init_at (dfd=9, path=0x7ffff72f1a5c ".", follow=1, out_dfd_iter=0x7fffffffd700, error=0x0)
    at libglnx/glnx-dirfd.c:106
#7  0x00007ffff72933bf in cleanup_tmpdir (self=0x55555586b040, cancellable=0x0, error=0x0) at src/libostree/ostree-repo-commit.c:1761
#8  0x00007ffff729416d in ostree_repo_abort_transaction (self=0x55555586b040, cancellable=0x0, error=0x0) at src/libostree/ostree-repo-commit.c:2176
#9  0x000055555558637d in  ()
#10 0x00005555555714cd in  ()
#11 0x00007ffff57d21c1 in __libc_start_main (main=
```

ostree fails with an error caused by gpgme (https://github.com/ostreedev/ostree/pull/1579) and something causes the abort path to fail, which may also be an ostree bug.

I created this before here: https://github.com/flatpak/flatpak-builder/issues/115

Funnily enough, when I compile ostree with `-fsanitize=address` I cannot reproduce the crash. It fails nicely as expected.

**Comment by Mikenux** [comment]
@muelli: Has this been fixed since then?

**Comment by muelli** [comment]
no idea :-/
