### ISSUE TITLE
X11 auth problems when hostname changes

### ISSUE THREAD

**Issue by Speirs47** [flatpak/flatpak#1821]
## Linux distribution and version
OpenSuse Leap 15.0 (with Plasma desktop)
## Flatpak version
0.11.7 (and also 0.10.4)
## Description of the problem
I have a problem starting flatpak apps (Spotify and openTTD). When I click an icon in apps drawer it will seem that it is starting but after a second it just crash.
When I try to start an app with Konsole I get this errors:
`> flatpak run com.spotify.Client `
`No protocol specified`
`Could not determine display scale factor, running with default.`
`/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)`
`Gtk-Message: Failed to load module "canberra-gtk-module"`
`No protocol specified`
`(spotify:5): Gtk-WARNING **: cannot open display: :99.0`
`Traceback (most recent call last):`
`  File "/app/bin/spotify", line 18, in <module>`
`    subprocess.check_call(argv)`
`  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call`
`    raise CalledProcessError(retcode, cmd)`
`subprocess.CalledProcessError: Command '['/app/extra/bin/spotify']' returned non-zero exit status 1`

`> flatpak run org.openttd.OpenTTD `
`No protocol specified`
`No protocol specified`
`Error: Couldn't find any suitable video driver`

I think the key clue is "cannot open display" error while starting spotify.
When I start these apps as the first thing when I login, they will probably start. I think it might be related to network connection (maybe just WiFi).
## Steps to reproduce
Hard to tell as it doesn't always occur. Most likely way to reproduce is:
1. Reboot computer.
2. Login
3. Wait for WiFi connection to establish.
4. Try to start any of those apps
5. No profit

**Comment by Speirs47** [comment]
Running `xhost +` helps but only untill a reboot

**Comment by alexlarsson** [comment]
When this happens, do you have a /tmp/.X11-unix directory on the host? And if so, what is in it?
Also can you `flatpak run -v com.spotify.Client` and see what that says.

**Comment by Speirs47** [comment]
> filip@NORM07:/tmp/.X11-unix> ls -l
razem 0
srwxrwxrwx 1 root root 0 06-27 10:27 X0

> filip@NORM07:~> flatpak run -v com.spotify.Client 
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path /home/filip/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/filip/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Allowing dri access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/filip/.config/pulse/client.conf': Błąd podczas otwierania pliku /home/filip/.config/pulse/client.conf: Nie ma takiego pliku ani katalogu
No protocol specified
Could not determine display scale factor, running with default.
/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
Gtk-Message: Failed to load module "canberra-gtk-module"
No protocol specified
(spotify:5): Gtk-WARNING **: cannot open display: :99.0
Traceback (most recent call last):
  File "/app/bin/spotify", line 18, in <module>
    subprocess.check_call(argv)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/app/extra/bin/spotify']' returned non-zero exit status 1

**Comment by alexlarsson** [comment]
Can you try running "xhost +" on the host first?

**Comment by alexlarsson** [comment]
Oh, i see you did that. It seems to be some issue with X authentication then...

**Comment by Speirs47** [comment]
For me it seems to be something wrong with hostnames.

> filip@NORM07:> echo $XAUTHLOCALHOSTNAME 
NORM07

> filip@NORM07:> hostname
NORM07.nordprim.local

And when I access Network Settings in openSUSE's Yast I see my hostname set as 'localhost'. When I change it to a valid hostname (so hostname is `NORM07` and domain name `nordprim.local`) then `echo $XAUTHLOCALHOSTNAME` and `hostname` commands returns the same result (`NORM07`).
I already reported it on openSUSE forums and bugzilla but I can't get any respond to that.

Overall it seems that Network Manager is changing the hostname when it connects to a network

**Comment by Speirs47** [comment]
I got it. Found it in another openSUSE's bug report and it does the trick. Not sure if it fixes the problem permanently yet.

> hostnamectl --static set-hostname NORM07

**Comment by venekamp** [comment]
Seems that I am having the same issue and a do switch networks multiple times a day. I am on openSUSE Tumbleweed. Haven't done a network switch after applying the suggested fix.

**Comment by alexlarsson** [comment]
Normally distros are set up to connect to X with unix domain sockets and auth by using the get-peer-uid feature of that. But if that is not happening we fall back to copying the x magic cookie for the current display from ~/.Xauthority, which is happening here:
https://github.com/flatpak/flatpak/blob/master/common/flatpak-run.c#L85

So, there are two issues. 1) Why is it not using the normal auth, and 2) why does the xauth forwarning break.

**Comment by venekamp** [comment]
I have changed the moment at which I start flatpak apps. It used to be during desktop startup, which is KDE for me. Now I don't and start them until after the desktop is fully up and running. I don't think I have run into the issue anymore.

I don't know if the above is useful or not. Is there anything I could do to get a more definitive answer for you?

**Comment by smcv** [comment]
> Why is it not using the normal auth

Because not all distros and not all desktop environments have caught up with the fact that they can do the equivalent of `xhost +si:localuser:$(id -nu)`, which you think of as "normal" because you're using a high-quality distro and/or desktop environment implementation. I thought the same, because I use GNOME on Debian, both of which do that - until I tested on other desktop environments and distros, some of which don't.

> why does the xauth forwarding break

Because this particular machine's networking setup is arbitrarily changing the hostname to whatever DHCP told it to think its name was; and MIT magic cookie (XAUTHORITY) authentication records are keyed by hostname, so if your hostname changes, they all get invalidated.

I think that's a distro integration bug, or possibly local misconfiguration. If the distro set a static hostname during installation and didn't overwrite it with the DHCP hostname, that would solve this by not having the hostname change. Or, if the distro did the equivalent of `xhost +si:localuser:$(id -nu)`, that would solve this by making X11 authentication work the same way as D-Bus authentication - "your uid is the same as my uid, so you may connect" - which bypasses any dependency on the hostname.
