### ISSUE TITLE
flatpak-coredumpctl should offer to install SDKs

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak#2003]
Using flatpak-0.99.3-1.fc28.x86_64

```
$ flatpak-coredumpctl org.gnome.Rhythmbox3//stable
Executable /app/bin/rhythmbox doesn't seem to be a flatpaked application.
Running: `"flatpak" "run" "--filesystem=/tmp" "--command=gdb" "--devel" "org.gnome.Rhythmbox3//stable" "/app/bin/rhythmbox" "/tmp/tmpintygcif"`
error: runtime/org.gnome.Sdk/x86_64/3.26 not installed
Traceback (most recent call last):
  File "/usr/bin/flatpak-coredumpctl", line 83, in <module>
    coredumper.run()
  File "/usr/bin/flatpak-coredumpctl", line 58, in run
    subprocess.check_call(flatpak_command)
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['flatpak', 'run', '--filesystem=/tmp', '--command=gdb', '--devel', 'org.gnome.Rhythmbox3//stable', '/app/bin/rhythmbox', '/tmp/tmpintygcif']' returned non-zero exit status 1.
```

**Comment by hadess** [comment]
And the necessary `.Debug` extensions, see #2004
