### ISSUE TITLE
prints a lot of whitespace when trying to install something

### ISSUE THREAD

**Issue by ocrete** [flatpak/flatpak#251]
When trying to install something in F24, flatpak prints a lot of whitespace! If I ctrl-c the "flatpak install" and restart it, it seems to work fine.

strace does:
```
write(1, "                                "..., 1024) = 1024
write(1, "                                "..., 1024) = 1024
write(1, "                                "..., 1024) = 1024
write(1, "                                "..., 1024) = 1024
write(1, "                                "..., 1024) = 1024
write(1, "                                "..., 1024) = 1024
write(1, "                                "..., 1024) = 1024
write(1, "                                "..., 1024) = 1024
write(1, "                                "..., 1024) = 1024
write(1, "                                "..., 1024) = 1024
write(1, "                                "..., 1024) = 1024
write(1, "                                "..., 1024) = 1024
write(1, "                                "..., 1024) = 1024
write(1, "                                "..., 1024) = 1024
write(1, "                                "..., 1024) = 1024
```
And gdb says:
```
#0  0x00007f39b47f6fed in write () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f39b477ab0f in _IO_new_file_write (f=0x7f39b4ac1600 <_IO_2_1_stdout_>, data=0x56215c7e0500, n=1024) at fileops.c:1263
#2  0x00007f39b477c269 in _IO_new_do_write (to_do=1024, data=0x56215c7e0500 ' ' <repeats 200 times>..., fp=0x7f39b4ac1600 <_IO_2_1_stdout_>)
    at fileops.c:518
#3  0x00007f39b477c269 in _IO_new_do_write (fp=0x7f39b4ac1600 <_IO_2_1_stdout_>, data=0x56215c7e0500 ' ' <repeats 200 times>..., to_do=1024)
    at fileops.c:494
#4  0x00007f39b477b390 in _IO_new_file_xsputn (f=0x7f39b4ac1600 <_IO_2_1_stdout_>, data=<optimized out>, n=20) at fileops.c:1331
#5  0x00007f39b47707a6 in __GI__IO_fwrite (buf=buf@entry=0x7f39b5f6a220 <spaces>, size=size@entry=1, count=count@entry=20, fp=0x7f39b4ac1600 <_IO_2_1_stdout_>) at iofwrite.c:39
#6  0x00007f39b5f5c6c1 in printpad (padbuf=padbuf@entry=0x7f39b5f6a220 <spaces> ' ' <repeats 20 times>, n=n@entry=4294967292, padbuf_len=20)
    at libglnx/glnx-console.c:176
#7  0x00007f39b5f5c9f6 in text_percent_internal (text=0x56215c7e0470 "Receiving delta parts: 0/9 553.0 kB/s 2.2 MB/178.0 MB 5 minutes 17 seconds remaining", percentage=percentage@entry=-1) at libglnx/glnx-console.c:226
#8  0x00007f39b5f5cbca in glnx_console_text (text=<optimized out>) at libglnx/glnx-console.c:282
#9  0x00007f39b5f1f401 in ostree_repo_pull_default_console_progress_changed (progress=<optimized out>, user_data=<optimized out>)
    at src/libostree/ostree-repo.c:3936
#10 0x00007f39b565b617 in _g_closure_invoke_va (closure=closure@entry=0x56215c7c42e0, return_value=return_value@entry=0x0, instance=instance@entry=0x7f399c004590, args=args@entry=0x7fff600a4f70, n_params=<optimized out>, param_types=0x0) at gclosure.c:867
#11 0x00007f39b5675ea9 in g_signal_emit_valist (instance=0x7f399c004590, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fff600a4f70)
    at gsignal.c:3294
#12 0x00007f39b56764ff in g_signal_emit (instance=instance@entry=0x7f399c004590, signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3441
#13 0x00007f39b5f10ef7 in idle_invoke_async_progress (user_data=0x7f399c004590) at src/libostree/ostree-async-progress.c:168
#14 0x00007f39b5387703 in g_main_context_dispatch (context=0x56215c7a6a20) at gmain.c:3154
#15 0x00007f39b5387703 in g_main_context_dispatch (context=context@entry=0x56215c7a6a20) at gmain.c:3769
#16 0x00007f39b5387ab0 in g_main_context_iterate (context=context@entry=0x56215c7a6a20, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3840
#17 0x00007f39b5387b5c in g_main_context_iteration (context=0x56215c7a6a20, may_block=may_block@entry=1) at gmain.c:3901
#18 0x00007f39b5f2f784 in ostree_repo_pull_with_options (self=<optimized out>, remote_name_or_baseurl=<optimized out>, options=<optimized out>, progress=<optimized out>, cancellable=0x0, error=0x7fff600a58d8) at src/libostree/ostree-repo-pull.c:2749
#19 0x000056215aa1cecf in repo_pull_one_dir ()
#20 0x000056215aa21d5f in flatpak_dir_pull ()
#21 0x000056215aa29007 in flatpak_dir_install ()
#22 0x000056215aa05609 in flatpak_builtin_install ()
#23 0x000056215aa02d66 in flatpak_run ()
#24 0x000056215aa02412 in main ()
```

**Comment by dbnicholson** [comment]
I might be wrong, but I believe this is a libglnx issue fixed by https://git.gnome.org/browse/libglnx/commit/?id=c072ef1ebab052bdecb0d9a52c14813728f83859, which actually manifests in ostree. I've seen similar using just ostree.

**Comment by alexlarsson** [comment]
If so, ostree 2016.7 should fix it. Can anyone reproduce with that?

**Comment by ocrete** [comment]
Seems to work fine with ostree 2017.7 on F24 now, thanks you!
