### ISSUE TITLE
Throws ostree errors when repo doesn't exist

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak#270]
```
flatpak-0.6.9-1.fc24.x86_64
ostree-2016.7-1.fc24.x86_64
```

Running `flatpak update`, using https://github.com/hadess/gnu-hello-flatpak

```
(/usr/bin/flatpak update:25371): OSTree-CRITICAL **: ostree_repo_open: assertion 'error == NULL || *error == NULL' failed
```

```
#0  0x00007ffff6d4019b in g_logv (breakpoint=1) at gmessages.c:325
#1  0x00007ffff6d4019b in g_logv (log_domain=0x7ffff7913f38 "OSTree", log_level=G_LOG_LEVEL_CRITICAL, format=<optimized out>, args=args@entry=0x7fffffffd850) at gmessages.c:1080
#2  0x00007ffff6d4030f in g_log (log_domain=log_domain@entry=0x7ffff7913f38 "OSTree", log_level=log_level@entry=G_LOG_LEVEL_CRITICAL, format=format@entry=0x7ffff6d89e50 "%s: assertion '%s' failed")
    at gmessages.c:1119
#3  0x00007ffff6d40349 in g_return_if_fail_warning (log_domain=log_domain@entry=0x7ffff7913f38 "OSTree", pretty_function=pretty_function@entry=0x7ffff7915bf0 <__func__.32080> "ostree_repo_open", expression=expression@entry=0x7ffff7915788 "error == NULL || *error == NULL") at gmessages.c:1134
#4  0x00007ffff78ce324 in ostree_repo_open (self=self@entry=0x555555834b40 [OstreeRepo], cancellable=cancellable@entry=0x0, error=error@entry=0x7fffffffdbf0) at src/libostree/ostree-repo.c:2108
#5  0x000055555558892d in flatpak_dir_create_system_child_repo (self=self@entry=0x5555557e1ee0 [FlatpakDir], file_lock=file_lock@entry=0x7fffffffdb40, error=error@entry=0x7fffffffdbf0)
    at common/flatpak-dir.c:2995
#6  0x0000555555590722 in flatpak_dir_update (self=self@entry=0x5555557e1ee0 [FlatpakDir], no_pull=0, no_deploy=0, ref=ref@entry=0x555555811f20 "app/org.gnu.hello/x86_64/master", remote_name=remote_name@entry=0x5555557f58c0 "org.gnu.hello-origin", checksum_or_latest=0x0, opt_subpaths=0x0, progress=0x0, cancellable=0x0, error=0x7fffffffdbf0) at common/flatpak-dir.c:3373
#7  0x000055555556b462 in do_update (dir=0x5555557e1ee0 [FlatpakDir], ref=0x555555811f20 "app/org.gnu.hello/x86_64/master", cancellable=cancellable@entry=0x0, error=error@entry=0x7fffffffdd18)
    at app/flatpak-builtins-update.c:103
#8  0x000055555556bcde in flatpak_builtin_update (argc=<optimized out>, argv=<optimized out>, cancellable=0x0, error=0x7fffffffdd18) at app/flatpak-builtins-update.c:255
#9  0x0000555555567546 in flatpak_run (argc=<optimized out>, argv=<optimized out>, res_error=0x7fffffffdd88) at app/flatpak-main.c:361
#10 0x0000555555566bf2 in main (argc=2, argv=0x7fffffffdea8) at app/flatpak-main.c:449
```

The gnu hello was installed from a .flatpak file:
```
$ flatpak remote-list --show-details org.gnu.hello
gnome                -                           https://sdk.gnome.org/repo/                                   1              
gnome-apps           -                           https://sdk.gnome.org/repo-apps/                              1              
gnome-nightly        -                           http://sdk.gnome.org/nightly/repo/                            1              
gnome-nightly-apps   -                           http://sdk.gnome.org/nightly/repo-apps/                       1              
gnome-x86-tmp        -                           http://sdkbuilder1.gnome.org/repo/                            1              
hello-repo           -                           file:///home/hadess/Projects/jhbuild/hello-flatpak/hello-repo 1 no-gpg-verify
org.gnu.hello-origin org.gnu.hello.x86_64.xdgapp                                                               0 no-enumerate 
```

The `hello-repo` entry doesn't exist any more. A better error message would be nice, rather than the double-error.

**Comment by hadess** [comment]
Seems it really is the location for "org.gnu.hello-origin" as created by the flatpak that fails:
```
$ flatpak remote-delete hello-repo
$ flatpak update
Updating application org.gnu.hello, branch master

(flatpak update:25844): OSTree-CRITICAL **: ostree_repo_open: assertion 'error == NULL || *error == NULL' failed
error: Invalid URL ''
$ flatpak remote-delete org.gnu.hello-origin
error: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code0: Can't remove remote 'org.gnu.hello-origin' with installed ref app/org.gnu.hello/x86_64/master (at least)
$ flatpak remote-list --show-details org.gnu.hello
gnome                -                           https://sdk.gnome.org/repo/             1             
gnome-apps           -                           https://sdk.gnome.org/repo-apps/        1             
gnome-nightly        -                           http://sdk.gnome.org/nightly/repo/      1             
gnome-nightly-apps   -                           http://sdk.gnome.org/nightly/repo-apps/ 1             
gnome-x86-tmp        -                           http://sdkbuilder1.gnome.org/repo/      1             
org.gnu.hello-origin org.gnu.hello.x86_64.xdgapp                                         0 no-enumerate

```
