### ISSUE TITLE
Unable to establish a IBus connection

### ISSUE THREAD

**Issue by subins2000** [flatpak/flatpak#3019]
## Linux distribution and version
Ubuntu 18.04
## Flatpak version
Flatpak 1.0.8
## Description of the problem
I'm trying to package this [IBus engine](https://github.com/varnamproject/libvarnam-ibus). Here's the [packaging repo](https://github.com/subins2000/varnam-flatpak). I gave enough permissions for the engine to connect to parent `ibus-daemon` but it fails :
```
GLib-GIO _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?IBUS ibus_factory_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failedGLib-GObject g_object_ref_sink: assertion 'G_IS_OBJECT (object)' failedIBUS ibus_factory_add_engine: assertion 'IBUS_IS_FACTORY (factory)' failedIBUS ibus_bus_call_sync: assertion 'ibus_bus_is_connected (bus)' failed
```

To test if it's a connection problem, I ran the default [ibus-tmpl engine](https://github.com/ibus/ibus-tmpl), but that also fails establishing a connection :
```
Traceback (most recent call last):
  File "main.py", line 121, in <module>
    main()
  File "main.py", line 118, in main
    launch_engine(exec_by_ibus)
  File "main.py", line 78, in launch_engine
    IMApp(exec_by_ibus).run()
  File "main.py", line 59, in __init__
    self.__factory = IBus.Factory.new(self.__bus.get_connection())
TypeError: Argument 0 does not allow None as a value
```
So it seems that it is failing in a connection to ibus. I read #675, perhaps flatpak is limiting the access of an engine ?

Does flatpak's implementation of ibus portal supports packaging an engine ?
Or am I doing it wrong ? Here are the [permissions](https://github.com/subins2000/varnam-flatpak/blob/ibus/com.varnamproject.Varnam.json) :
```json
"finish-args": [
        "--share=ipc",
        "--own-name=org.freedesktop.IBus.EnchantPython",
        "--talk-name=org.freedesktop.DBus",
        "--talk-name=org.freedesktop.IBus",
        "--talk-name=org.freedesktop.portal.IBus",
        "--filesystem=xdg-run/dconf",
        "--filesystem=~/.config/dconf:ro",
        "--talk-name=ca.desrt.dconf",
        "--env=DCONF_USER_CONFIG_DIR=.config/dconf"
],
```

**Comment by AnwarShah** [comment]
I have a similar problem, though I haven't started packaging yet

**Comment by subins2000** [comment]
@AnwarShah what problem do you face ? Is the debug/error message similar to this ?

**Comment by AnwarShah** [comment]
I haven't gone to packaging. I am assessing whether it is possible to use flatpak for providing ibus engine to be used by system ibus.

**Comment by mominul** [comment]
I am maintaining an iBus engine, so I am also interested in this issue.

**Comment by subins2000** [comment]
@mominul Nice to see there's a Bangla ibus engine :)

Can you try packaging it ? Perhaps another set of eyes will help in making it work. I don't know C much and haven't got into the engine's code. I'm just trying to package it.

**Comment by mominul** [comment]
@subins2000 Thanks for your appreciation!

But I want to know about is it possible to pack IMEs with Flatpak in the first place as IME(ibus engines) might require special permissions. I don't have enough knowledge of dbus or Flatpak to know if this is possible. It'd be great if a person familiar with Flatpak would help us.

cc @fujiwarat @matthiasclasen

**Comment by fujiwarat** [comment]
Do you have ibus-portal?
https://github.com/ibus/ibus/tree/master/portal

**Comment by subins2000** [comment]
@fujiwarat This should included in the flatpak package ?

**Comment by fujiwarat** [comment]
ibus-portal is running in the host side. and sandbox also should include GTK IM module for IBus.
I mean old IBus version does not implement ibus-portal.

**Comment by subins2000** [comment]
@fujiwarat I'm using Ubuntu 18.04. Is `ibus-portal` installed from the default `ibus` package (`ibus amd64 1.5.17-3ubuntu5`) in official repos ? How do I know if it's running ?

How do I include GTK IM module in sandbox ? Any examples ?

**Comment by mominul** [comment]
I think you have to use the latest version https://github.com/ibus/ibus/releases

**Comment by fujiwarat** [comment]
ibus 1.5.17 has ibus-portal. You can check it's running with `ps` command.
You can find im-ibus.so with `find` command in your sandbox. E.g. org.freedesktop.Platform and org.gnome.Platform includes IBus GTK IM module.
If your application uses Atom applications, you need ibus 1.5.20 or later.

**Comment by subins2000** [comment]
@fujiwarat Just checked, I have `1.5.17`, `ibus-portal` is running and the sandbox has `im-ibus.so (org.freedesktop.Platform). But the error still comes :

```
GVFS-RemoteVolumeMonitor Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
GVFS cannot open directory /usr/share/gvfs/remote-volume-monitors: Error opening directory ?/usr/share/gvfs/remote-volume-monitors?: No such file or directoryGVFS org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)
GLib-GIO _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?IBUS ibus_factory_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failedGLib-GObject g_object_ref_sink: assertion 'G_IS_OBJECT (object)' failedIBUS ibus_factory_add_engine: assertion 'IBUS_IS_FACTORY (factory)' failedIBUS ibus_bus_call_sync: assertion 'ibus_bus_is_connected (bus)' failed
```

**Comment by fujiwarat** [comment]
Sorry, I misread your issue. You tries to package an ibus engine but not application.
IBus assumes to run IBus engines in the host side but not sandbox.
You can run applications in the sandbox.

**Comment by subins2000** [comment]
@fujiwarat so there's no way to package an IBus engine with flatpak ? Or any workarounds or something ?

**Comment by fujiwarat** [comment]
There is no way and necessary for ibus engines.

**Comment by subins2000** [comment]
@fujiwarat It would be useful for packaging and distributing engines across various distros with ease. So I guess this issue would be a feature request for flatpak and IBus.

**Comment by fujiwarat** [comment]
There is no reason to run ibus-daemon in host and engines in sandbox.

**Comment by TingPing** [comment]
Flatpak cannot install libs to the host so this isn't even a feature request for Flatpak. It seems this is just how ibus is designed and intended to work.
