### ISSUE TITLE
Flatpak and Python USB core (PyUSB)

### ISSUE THREAD

**Issue by leinardi** [flatpak/flatpak#3022]
## Linux distribution and version
Ubuntu 19.04

## Flatpak version
Flatpak 1.4.2

## Description of the problem
I'm trying to create a flatpak for [GKraken](https://gitlab.com/leinardi/gkraken), I made everything work but the USB connection with the pump itself.

When I try to run the app it fails with the following error:
```
        main.py:299  2019-07-21 22:31:05,969: ERROR/ThreadPoolExecutor-0_0(2) Err = No backend available
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/rx/core/observable/defer.py", line 29, in subscribe
    result = factory(scheduler)
  File "/app/lib/python3.7/site-packages/gkraken/interactor.py", line 44, in <lambda>
    return rx.defer(lambda _: rx.just(self._kraken_repository.get_status()))
  File "/app/lib/python3.7/site-packages/gkraken/util/concurrency.py", line 23, in synced_method
    return method(self, *args, **kws)
  File "/app/lib/python3.7/site-packages/gkraken/repository.py", line 48, in get_status
    self._load_driver()
  File "/app/lib/python3.7/site-packages/gkraken/repository.py", line 81, in _load_driver
    self._driver = INJECTOR.get(Optional[KrakenTwoDriver])
  File "/app/lib/python3.7/site-packages/injector/__init__.py", line 802, in get
    result = scope_instance.get(key, binding.provider).get(self)
  File "/app/lib/python3.7/site-packages/injector/__init__.py", line 192, in get
    return injector.call_with_injection(self._callable)
  File "/app/lib/python3.7/site-packages/injector/__init__.py", line 885, in call_with_injection
    return callable(*full_args, **dependencies)
  File "/app/lib/python3.7/site-packages/gkraken/di.py", line 88, in provide_kraken_two_driver
    return next((dev for dev in find_all_supported_devices() if isinstance(dev, KrakenTwoDriver)), None)
  File "/app/lib/python3.7/site-packages/liquidctl/cli.py", line 76, in find_all_supported_devices
    return itertools.chain(*res)
  File "/app/lib/python3.7/site-packages/liquidctl/cli.py", line 75, in <lambda>
    res = map(lambda driver: driver.find_supported_devices(), DRIVERS)
  File "/app/lib/python3.7/site-packages/liquidctl/driver/base_usb.py", line 57, in find_supported_devices
    usbdevs = usb.core.find(idVendor=vid, idProduct=pid, find_all=True)
  File "/app/lib/python3.7/site-packages/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
```
I'm providing `pyusb`:
https://github.com/leinardi/flathub/blob/71b5d9b8ef835d5d534557b3b295275dc231c897/python3-liquidctl.json#L15

I added the permission `--device=all` to the flatpak manifest.

Is there anything else should I do to access USB peripherals from a flatpak?

## Steps to reproduce
You can clone the following branch: https://gitlab.com/leinardi/gkraken/tree/flatpak
You must also clone the submodules recursively to add the flathub repository: https://github.com/leinardi/flathub/tree/com.leinardi.gkraken

Once properly cloned, it can be build with `./build.sh --flatpak-local --flatpak-install` and run with `flatpak run com.leinardi.gkraken --debug`.

**Comment by TingPing** [comment]
Sounds like you don't have libusb built for it to use.

**Comment by leinardi** [comment]
Yep! Solved adding libusb!
```
{
    "name": "libusb",
    "config-opts": [ "--disable-static", "--disable-udev" ],
    "cleanup": [
        "/lib/*.la",
        "/lib/pkgconfig",
        "/include"
    ],
    "sources": [
        {
            "type": "archive",
            "url": "https://github.com/libusb/libusb/archive/v1.0.22.tar.gz",
            "sha256": "3500f7b182750cd9ccf9be8b1df998f83df56a39ab264976bdb3307773e16f48"
        }
    ],
    "post-install": [
        "install -Dm644 COPYING /app/share/licenses/libusb/COPYING"
    ]
}
```
Not sure if the config-opts are actually needed, I found this snipped on another flatpak project.

Thank you @TingPing, you are as always very helpful :+1:
