### ISSUE TITLE
Assertion failure during flatpak update : pull_data->n_outstanding_metadata_fetches > 0

### ISSUE THREAD

**Issue by LaurentBonnaud** [flatpak/flatpak#355]
I am using this package:

Package: flatpak
Version: 0.6.12-0alexlarsson1~xenial1

and flatpak crashes every time when it tries to update org.gnome.Maps:

```
# flatpak update
Updating application net.scribus.ScribusDevel, branch master
No updates.
Updating application org.darktable.DarktableDevel, branch master
No updates.
Updating related: org.darktable.DarktableDevel.Locale
No updates.
Updating application org.gimp.GimpDevel, branch master
No updates.
Updating related: org.gimp.GimpDevel.Locale
No updates.
Updating application org.gnome.Epiphany, branch master
No updates.
Updating related: org.gnome.Epiphany.Locale
No updates.
Updating application org.gnome.Epiphany, branch stable
No updates.
Updating related: org.gnome.Epiphany.Locale
No updates.
Updating application org.gnome.Evince, branch master
No updates.
Updating related: org.gnome.Evince.Locale
No updates.
Updating application org.gnome.Evince, branch stable
No updates.
Updating related: org.gnome.Evince.Locale
No updates.
Updating application org.gnome.Glade, branch master
No updates.
Updating related: org.gnome.Glade.Locale
No updates.
Updating application org.gnome.Glade, branch stable
No updates.
Updating related: org.gnome.Glade.Locale


Error updating: While pulling runtime/org.gnome.Glade.Locale/x86_64/stable from remote gnome-apps, metadata: GPG signatures found, but none are in trusted keyring
Updating application org.gnome.Maps, branch master

**
OSTree:ERROR:src/libostree/ostree-repo-pull.c:872:meta_fetch_on_complete: assertion failed: (pull_data->n_outstanding_metadata_fetches > 0)
Aborted (core dumped)
```

**Comment by hadess** [comment]
Please gather a backtrace of the crash.

**Comment by LaurentBonnaud** [comment]
Here it is:

```
# gdb /usr/bin/flatpak
	GNU gdb (Ubuntu 7.12-0ubuntu1) 7.12
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/flatpak...(no debugging symbols found)...done.
(gdb) run update
Starting program: /usr/bin/flatpak update
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Looking for updates...
[New Thread 0x7fffef53c700 (LWP 11047)]
[New Thread 0x7fffeed3b700 (LWP 11048)]
[Thread 0x7fffef53c700 (LWP 11047) exited]
[New Thread 0x7fffef53c700 (LWP 11063)]
[New Thread 0x7fffed467700 (LWP 11064)]
[Thread 0x7fffef53c700 (LWP 11063) exited]
[New Thread 0x7fffef53c700 (LWP 11071)]
[Thread 0x7fffef53c700 (LWP 11071) exited]
[New Thread 0x7fffef53c700 (LWP 11078)]
[Thread 0x7fffef53c700 (LWP 11078) exited]
[New Thread 0x7fffef53c700 (LWP 11085)]
[Thread 0x7fffef53c700 (LWP 11085) exited]
[New Thread 0x7fffef53c700 (LWP 11092)]
[Thread 0x7fffef53c700 (LWP 11092) exited]
[New Thread 0x7fffef53c700 (LWP 11094)]
[Thread 0x7fffef53c700 (LWP 11094) exited]
[New Thread 0x7fffef53c700 (LWP 11096)]
Warning: Problem looking for related refs: Could not connect: Connection refused
[Thread 0x7fffef53c700 (LWP 11096) exited]
Updating: org.gnome.Platform/x86_64/3.20 from gnome
No updates.
Updating: org.gnome.Platform.Locale/x86_64/3.20 from gnome

[New Thread 0x7fffef53c700 (LWP 11098)]
[New Thread 0x7fffef53c700 (LWP 11105)]
[Thread 0x7fffef53c700 (LWP 11098) exited]
[Thread 0x7fffef53c700 (LWP 11105) exited]
[New Thread 0x7fffef53c700 (LWP 11108)]
[Thread 0x7fffef53c700 (LWP 11108) exited]
[New Thread 0x7fffef53c700 (LWP 11115)]
1 metadata, 0 content objects fetched; 313 B transferred in 1 seconds                                                                         [Thread 0x7fffef53c700 (LWP 11115) exited]
1 metadata, 0 content objects fetched; 313 B transferred in 1 seconds                                                                         
No updates.
Updating: net.scribus.ScribusDevel/x86_64/master from nightly-graphics
No updates.
Updating: org.darktable.DarktableDevel/x86_64/master from nightly-graphics
No updates.
Updating: org.darktable.DarktableDevel.Locale/x86_64/master from nightly-graphics
No updates.
Updating: org.gimp.GimpDevel/x86_64/master from nightly-graphics
No updates.
Updating: org.gimp.GimpDevel.Locale/x86_64/master from nightly-graphics
No updates.
Updating: org.gnome.Platform/x86_64/master from gnome-nightly
No updates.
Updating: org.gnome.Platform.Locale/x86_64/master from gnome-nightly
No updates.
Updating: org.gnome.Epiphany/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Epiphany.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Platform/x86_64/3.22 from gnome
No updates.
Updating: org.gnome.Platform.Locale/x86_64/3.22 from gnome
No updates.
Updating: org.gnome.Epiphany/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Epiphany.Locale/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Evince/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Evince.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Evince/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Evince.Locale/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Glade/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Glade.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Glade/x86_64/stable from gnome-apps
No updates.
Installing: org.gnome.Glade.Locale/x86_64/stable from gnome-apps

[New Thread 0x7fffef53c700 (LWP 11118)]
[Thread 0x7fffef53c700 (LWP 11118) exited]
[New Thread 0x7fffef53c700 (LWP 11125)]

Warning: Failed to install org.gnome.Glade.Locale/x86_64/stable: While pulling runtime/org.gnome.Glade.Locale/x86_64/stable from remote gnome-apps: GPG signatures found, but none are in trusted keyring
Updating: org.gnome.Maps/x86_64/master from gnome-nightly-apps

[New Thread 0x7fffec793700 (LWP 11132)]
[New Thread 0x7fffebf92700 (LWP 11135)]
[Thread 0x7fffec793700 (LWP 11132) exited]
[New Thread 0x7fffec793700 (LWP 11140)]
**
OSTree:ERROR:src/libostree/ostree-repo-pull.c:928:meta_fetch_on_complete: assertion failed: (pull_data->n_outstanding_metadata_fetches > 0)

Thread 1 "flatpak" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
58	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff62d37ef in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#1  0x00007ffff62d53ea in __GI_abort () at abort.c:89
#2  0x00007ffff6d3d4d5 in g_assertion_message (domain=domain@entry=0x7ffff790f409 "OSTree", file=file@entry=0x7ffff7911fc8 "src/libostree/ostree-repo-pull.c", line=line@entry=928, func=func@entry=0x7ffff79129b0 "meta_fetch_on_complete", message=message@entry=0x555555ec2f70 "assertion failed: (pull_data->n_outstanding_metadata_fetches > 0)") at ././glib/gtestutils.c:2429
#3  0x00007ffff6d3d56a in g_assertion_message_expr (domain=0x7ffff790f409 "OSTree", file=0x7ffff7911fc8 "src/libostree/ostree-repo-pull.c", line=928, func=0x7ffff79129b0 "meta_fetch_on_complete", expr=<optimized out>) at ././glib/gtestutils.c:2452
#4  0x00007ffff78df5d7 in  () at /usr/lib/x86_64-linux-gnu/libostree-1.so.1
#5  0x00007ffff72bc4e3 in g_task_return_now (task=0x555555800bb0 [GTask]) at ././gio/gtask.c:1121
#6  0x00007ffff72bc519 in complete_in_idle_cb (task=0x555555800bb0) at ././gio/gtask.c:1135
#7  0x00007ffff6d1668a in g_main_dispatch (context=0x55555582b110) at ././glib/gmain.c:3201
#8  0x00007ffff6d1668a in g_main_context_dispatch (context=context@entry=0x55555582b110) at ././glib/gmain.c:3854
#9  0x00007ffff6d16a40 in g_main_context_iterate (context=context@entry=0x55555582b110, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ././glib/gmain.c:3927
#10 0x00007ffff6d16aec in g_main_context_iteration (context=0x55555582b110, may_block=1) at ././glib/gmain.c:3988
#11 0x00007ffff78e2a81 in ostree_repo_pull_with_options () at /usr/lib/x86_64-linux-gnu/libostree-1.so.1
#12 0x000055555558713e in  ()
#13 0x000055555558e512 in  ()
#14 0x000055555556a1db in  ()
#15 0x000055555556dcf5 in  ()
#16 0x0000555555569012 in  ()
#17 0x0000555555568752 in  ()
#18 0x00007ffff62be3f1 in __libc_start_main (main=
    0x555555568630, argc=2, argv=0x7fffffffe4b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe4a8) at ../csu/libc-start.c:291
#19 0x000055555556895a in  ()
(gdb) 

```

**Comment by LaurentBonnaud** [comment]
The previous backtrace lacks debug symbols for libostree, but the alexlarsson PPA does not provide a -dbg or -dbgsym package:

```
# apt install libostree-1-1-dbgsym
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libostree-1-1-dbgsym : Depends: libostree-1-1 (= 2016.10-1) but 2016.12-0alexlarsson1~yakkety1 is to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by alexlarsson** [comment]
Hmm, this looks like some issue inside ostree.

I don't really know PPAs well. Is there some way to make them create debug packages automatically?

**Comment by LaurentBonnaud** [comment]
> I don't really know PPAs well. Is there some way to make them create debug packages automatically?

Neither do I.  I don't know any PPA with debug packages.  Therefore my guess is that it is not possible or difficult :<.

**Comment by LaurentBonnaud** [comment]
I managed to get rid of this problem by removing and re-adding the affected bundles, but today the problem came back.

This is with those packages:
```
Package: flatpak
Version: 0.6.14-0alexlarsson1~yakkety1

Package: libostree-1-1
Version: 2016.14-0alexlarsson1~yakkety
```

Here is the failed assertion:

```
# flatpak update
Looking for updates...
Updating: org.gnome.Platform/x86_64/3.20 from gnome
No updates.
Updating: org.gnome.Platform.Locale/x86_64/3.20 from gnome

1 metadata, 0 content objects fetched; 313 B transferred in 1 seconds                                                                         
No updates.
Updating: net.scribus.ScribusDevel/x86_64/master from nightly-graphics
No updates.
Updating: org.darktable.DarktableDevel/x86_64/master from nightly-graphics
No updates.
Updating: org.darktable.DarktableDevel.Locale/x86_64/master from nightly-graphics
No updates.
Updating: org.gimp.GimpDevel/x86_64/master from nightly-graphics
No updates.
Updating: org.gimp.GimpDevel.Locale/x86_64/master from nightly-graphics
No updates.
Updating: org.gnome.Platform/x86_64/master from gnome-nightly
No updates.
Updating: org.gnome.Platform.Locale/x86_64/master from gnome-nightly
No updates.
Updating: org.gnome.Books/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Books.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Calculator/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Calculator.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Calendar/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Calendar.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Epiphany/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Epiphany.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Platform/x86_64/3.22 from gnome
No updates.
Updating: org.gnome.Platform.Locale/x86_64/3.22 from gnome
No updates.
Updating: org.gnome.Epiphany/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Epiphany.Locale/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Evince/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Evince.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Evince/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Evince.Locale/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Games/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Games.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Glade/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Glade.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Maps/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Maps.Locale/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Nautilus/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Nautilus.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Nautilus/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Nautilus.Locale/x86_64/stable from gnome-apps


Warning: Failed to update org.gnome.Nautilus.Locale/x86_64/stable: While pulling runtime/org.gnome.Nautilus.Locale/x86_64/stable from remote gnome-apps: GPG signatures found, but none are in trusted keyring
Updating: org.gnome.News/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.News.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Rhythmbox3/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Rhythmbox3.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Software.XdgApp/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Software.XdgApp.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Todo/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Todo.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Totem/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Totem.Locale/x86_64/stable from gnome-apps

**
OSTree:ERROR:src/libostree/ostree-repo-pull.c:927:meta_fetch_on_complete: assertion failed: (pull_data->n_outstanding_metadata_fetches > 0)
Aborted (core dumped)
```

**Comment by LaurentBonnaud** [comment]
After the recent repository updates this problem is now gone.
Therefore I am now closing this bug...  Thanks again!
