### ISSUE TITLE
flatpak remote-add: segfault upon failure to create /var/lib/flatpak

### ISSUE THREAD

**Issue by rekado** [flatpak/flatpak#3612]
## GNU/Linux distribution and version

Guix System

  guix fef052b
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: fef052b1b8238d6680437d62ce318e49922edb3

## Flatpak version
 
1.6.3

## Description of the problem

Flatpak segfaults when /var/lib/flatpak does not exist.  It crashes right after failing to create the directory due to lack of permissions.

## Steps to reproduce

```
$ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/rekado/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

Segmentation fault
```

Creating the directory manually works around the problem:

```
$ sudo mkdir /var/lib/flatpak
$ sudo chown me /var/lib/flatpak
$ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/rekado/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.
$
```

Alternatively, there's no segfault when passing `--user`.

**Comment by refi64** [comment]
Could you [install the debuginfo](http://guix.gnu.org/manual/en/html_node/Installing-Debugging-Files.html) and then:
- Run `gdb -ex run flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
- Let it crash
- Run `bt` to get a back trace

**Comment by mwleeds** [comment]
Arguably this is an issue with the way your distribution packaged Flatpak. At least, the way Debian creates the system flatpak installation is by running a flatpak command as root as part of the package installation process: https://salsa.debian.org/debian/flatpak/-/blob/c4d23d28d7e3b8ae721fc868e306449dd96f3761/debian/flatpak.postinst#L20

**Comment by rekado** [comment]
@mwleeds Guix package installation does not have side-effects by design.  I'd say a segfault is a pretty serious defect; flatpak should fail gracefully when it fails to create a directory.

**Comment by rekado** [comment]
Here's a preliminary backtrace indicating that the problem is with ostree:

```
(gdb) bt
#0  0x00007ffff73ea755 in g_mutex_lock () from /gnu/store/rmbxm1fg47b347kv1h5fb2w04nxqbsj6-glib-2.62.6/lib/libglib-2.0.so.0
#1  0x00007ffff7e299b7 in _ostree_repo_get_remote () from /gnu/store/p1zcchl9qjsc81rhw805p9lsgndjj1pj-libostree-2020.3/lib/libostree-1.so.1
#2  0x00007ffff7e29f73 in ostree_repo_get_remote_option () from /gnu/store/p1zcchl9qjsc81rhw805p9lsgndjj1pj-libostree-2020.3/lib/libostree-1.so.1
#3  0x00007ffff7e2b74c in ostree_repo_remote_get_url () from /gnu/store/p1zcchl9qjsc81rhw805p9lsgndjj1pj-libostree-2020.3/lib/libostree-1.so.1
#4  0x0000000000460c86 in flatpak_dir_cleanup_remote_for_url_change ()
#5  0x0000000000470689 in flatpak_dir_modify_remote ()
#6  0x000000000041c3f2 in flatpak_builtin_remote_add ()
#7  0x000000000041a926 in main ()
(gdb) 
```

**Comment by rekado** [comment]
Here's the full backtrace:

```
#0  0x00007ffff73ea755 in g_mutex_lock () from /gnu/store/rmbxm1fg47b347kv1h5fb2w04nxqbsj6-glib-2.62.6/lib/libglib-2.0.so.0
No symbol table info available.
#1  0x00007ffff7e299b7 in _ostree_repo_get_remote (self=0x0, name=0x7fffffffb419 "flathub", error=0x7fffffffaa78) at src/libostree/ostree-repo.c:700
        remote = 0x0
        _g_boolean_var_ = <optimized out>
#2  0x00007ffff7e29f73 in ostree_repo_get_remote_option (self=self@entry=0x0, remote_name=remote_name@entry=0x7fffffffb419 "flathub", 
    option_name=option_name@entry=0x7ffff7e8cdce "url", default_value=default_value@entry=0x0, out_value=out_value@entry=0x7fffffffaac8, 
    error=error@entry=0x0) at src/libostree/ostree-repo.c:817
        remote = 0x0
        ret = 0
        temp_error = 0x0
        value = 0x0
#3  0x00007ffff7e2b74c in ostree_repo_remote_get_url (self=0x0, name=name@entry=0x7fffffffb419 "flathub", out_url=out_url@entry=0x7fffffffab18, 
    error=error@entry=0x0) at src/libostree/ostree-repo.c:1985
        __func__ = "ostree_repo_remote_get_url"
        url = 0x0
#4  0x0000000000460c86 in flatpak_dir_cleanup_remote_for_url_change (self=self@entry=0x56a490, remote_name=remote_name@entry=0x7fffffffb419 "flathub", 
    url=url@entry=0x828950 "https://dl.flathub.org/repo/", cancellable=cancellable@entry=0x0, error=error@entry=0x7fffffffacf0)
    at common/flatpak-dir.c:13298
        old_url = 0x0
#5  0x0000000000470689 in flatpak_dir_modify_remote (self=self@entry=0x56a490, remote_name=remote_name@entry=0x7fffffffb419 "flathub", 
    config=config@entry=0x54a300, gpg_data=0x576e60, cancellable=cancellable@entry=0x0, error=error@entry=0x7fffffffacf0) at common/flatpak-dir.c:13384
        group = 0xb75140 "remote \"flathub\""
        url = 0x828950 "https://dl.flathub.org/repo/"
        metalink = 0x0
        new_config = 0x0
        filter_path = 0x0
        has_remote = <optimized out>
        config_data = <optimized out>
        gpg_data_v = <optimized out>
        installation = <optimized out>
#6  0x000000000041c3f2 in flatpak_builtin_remote_add (argc=<optimized out>, argv=<optimized out>, cancellable=0x0, error=<optimized out>)
    at app/flatpak-builtins-remote-add.c:389
        context = <optimized out>
        dirs = 0x54e320
        dir = <optimized out>
        file = 0x0
        remotes = 0x6e4860
        remote_url = 0x0
        remote_name = 0x7fffffffb419 "flathub"
        location = <optimized out>
        config = 0x54a300
        gpg_data = 0x576e60
        local_error = 0x0
#7  0x000000000041a926 in flatpak_run (res_error=0x7ffffffface0, argv=<optimized out>, argc=<optimized out>) at app/flatpak-main.c:766
        command = 0x4fa8e0 <commands+1440>
        success = 0
        error = 0x0
        cancellable = 0x0
        prgname = 0x54d7e0 "/home/rekado/.guix-profile/bin/flatpak remote-add"
        command_name = 0x7fffffffb3fe "remote-add"
        polkit_agent = 0x0
        command = <optimized out>
        error = <optimized out>
        cancellable = <optimized out>
        prgname = <optimized out>
        success = <optimized out>
        command_name = <optimized out>
        polkit_agent = <optimized out>
        context = <optimized out>
        hint = <optimized out>
        msg = <optimized out>
        similar = <optimized out>
        option = <optimized out>
        local_error = <optimized out>
        arches = <optimized out>
        i = <optimized out>
        drivers = <optimized out>
        i = <optimized out>
        paths = <optimized out>
        i = <optimized out>
        file = <optimized out>
        _g_boolean_var_ = <optimized out>
#8  main (argc=<optimized out>, argv=<optimized out>) at app/flatpak-main.c:881
        error = 0x0
        old_env = 0x0
        ret = <optimized out>
        action = {__sigaction_handler = {sa_handler = 0x41b380 <handle_sigterm>, sa_sigaction = 0x41b380 <handle_sigterm>}, sa_mask = {__val = {
              0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
```
