### ISSUE TITLE
Crash with flatpak install

### ISSUE THREAD

**Issue by hfiguiere** [flatpak/flatpak#4234]
## Linux distribution and version

Fedora 33

## Flatpak version

Flatpak 1.10.2

## Description of the problem

flatpak install crashes.

```
(gdb) r
Starting program: /usr/bin/flatpak install --user --reinstall ./.flatpak-builder/cache org.guitarix.Guitarix/x86_64/master
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.32-4.fc33.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe8d04640 (LWP 815806)]
[New Thread 0x7fffe3fff640 (LWP 815807)]
[New Thread 0x7fffe37fe640 (LWP 815808)]
Looking for matches…

Thread 1 "flatpak" received signal SIGSEGV, Segmentation fault.
flatpak_decomposed_get_ref (ref=ref@entry=0x0) at common/flatpak-ref-utils.c:1013
1013	  return (const char *)&ref->data[ref->ref_offset];
(gdb) where
#0  flatpak_decomposed_get_ref (ref=ref@entry=0x0) at common/flatpak-ref-utils.c:1013
#1  0x0000555555613076 in flatpak_dir_get_deploy_dir (ref=0x0, self=0x55555573b800) at common/flatpak-dir.c:2896
#2  flatpak_dir_get_if_deployed (self=0x55555573b800, ref=0x0, checksum=0x0, cancellable=0x0) at common/flatpak-dir.c:10724
#3  0x0000555555613508 in flatpak_dir_get_deploy_data (self=0x55555573b800, ref=0x0, required_version=0, cancellable=0x0, error=0x0) at common/flatpak-dir.c:3526
#4  0x000055555562cc16 in flatpak_dir_find_local_related_for_metadata
    (self=0x55555573b800, ref=<optimized out>, remote_name=0x0, metakey=0x55555583a140, cancellable=<optimized out>, error=<optimized out>) at common/flatpak-dir.c:15094
#5  0x000055555562dc88 in find_used_refs
    (self=0x55555573b800, shadowing_dir=0x0, arch=0x0, metadata_injection=0x555555865f60 = {...}, refs_to_exclude=0x0, used_refs=0x555555d79640 = {...}, cancellable=0x0, error=0x7fffffffdc08) at common/flatpak-dir.c:15910
#6  0x000055555562f82b in flatpak_dir_list_unused_refs
    (self=0x55555573b800, arch=arch@entry=0x0, metadata_injection=metadata_injection@entry=0x555555865f60 = {...}, eol_injection=eol_injection@entry=0x555555865d20 = {...}, refs_to_exclude=<optimized out>, filter_by_eol=filter_by_eol@entry=1, cancellable=0x0, error=0x7fffffffdc08) at common/flatpak-dir.c:15959
#7  0x000055555565e806 in add_uninstall_unused_ops (error=0x7fffffffdc08, cancellable=0x0, self=0x55555577e0e0) at common/flatpak-transaction.c:4543
#8  flatpak_transaction_real_run (self=0x55555577e0e0, cancellable=0x0, error=0x7fffffffdc08) at common/flatpak-transaction.c:4695
#9  0x00005555555e3a4e in flatpak_cli_transaction_run (transaction=0x55555577e0e0, cancellable=0x0, error=0x7fffffffdc08) at app/flatpak-cli-transaction.c:1388
#10 0x00005555555b26fe in flatpak_builtin_install (argc=<optimized out>, argv=<optimized out>, cancellable=0x0, error=0x7fffffffdc08) at app/flatpak-builtins-install.c:562
#11 0x00005555555a7d41 in flatpak_run (res_error=0x7fffffffdbf8, argv=<optimized out>, argc=<optimized out>) at app/flatpak-main.c:841
#12 main (argc=<optimized out>, argv=<optimized out>) at app/flatpak-main.c:946
(gdb) 
```
`ref` is `nullptr` (0x0).

## Steps to reproduce

Add this to the JSON manifest. Note: the "version" field is what makes it crash. "20.08" is fine.

```json
    "add-extensions": {
        "org.freedesktop.LinuxAudio.Plugins": {
            "directory": "extensions/Plugins",
            "version": "20.08;master",
            "add-ld-path": "lib",
            "merge-dirs": "ladspa;lv2",
            "subdirectories": true,
            "no-autodownload": true,
            "autodelete": false
        },
```

## Larger example:

- Checkout https://github.com/flathub/org.guitarix.Guitarix/
- Change the manifest to have the extension point like described above. (the "version" property)
- Build it with `flatpak-builder --force-clean --ccache --install --user repo org.guitarix.Guitarix.json`

it will end with 
```
Exporting org.freedesktop.LinuxAudio.Plugins.Guitarix to repo
Commit: 95dd0bdb126c997ab7629a2d8a4ec40fdd2c2b6b0f819b71d7a76dec6eba0510
Metadata Total: 153
Metadata Written: 1
Content Total: 281
Content Written: 0
Content Bytes Written: 0 (0 bytes)
Install failed: Child process killed by signal 11
```
And not being installed.

**Comment by hfiguiere** [comment]
Just to clarify I don't expect it to be valid (if it is then it's a different bug), but I expect to not crash. Which my patch addresses.

(Why would I want to do that is a different longer story)
