### ISSUE TITLE
[Bug]: transaction doesn't cancel when a webflow is ongoing

### ISSUE THREAD

**Issue by aleixpol** [flatpak/flatpak#4881]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

n/a

### What architecture are you using?

x86_64

### How to reproduce

I've reproduced it in Discover, issuing an installation of a test app that requires webflow. 

### Expected Behavior

flatpak_transaction_run should return immediately and return false like it does when it's in different states.

### Actual Behavior

Calling g_cancellable_cancel() during that time doesn't get the transaction cancelled.

Here's the backtrace I see, I guess I could get the debug symbols in somehow if necessary.

```
Thread 52 (Thread 0x7ffefe832640 (LWP 64181) "FlatpakTransact"):
#0  0x00007ffff51422af in poll () at /usr/lib/libc.so.6
#1  0x00007ffff2590976 in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x7ffee8033b70, timeout=<optimized out>, context=0x7ffee800b900) at ../glib/glib/gmain.c:4516
#2  g_main_context_iterate.constprop.0 (context=context@entry=0x7ffee800b900, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4206
#3  0x00007ffff25376c5 in g_main_context_iteration (context=0x7ffee800b900, may_block=1) at ../glib/glib/gmain.c:4276
#4  0x00007fffa84fe07e in  () at /usr/lib/libflatpak.so.0
#5  0x00007fffa84f7b94 in  () at /usr/lib/libflatpak.so.0
#6  0x00007fffa85e9637 in FlatpakTransactionThread::run() (this=0x555556a15550) at /home/apol/devel/frameworks/discover/libdiscover/backends/FlatpakBackend/FlatpakTransactionThread.cpp:172
#7  0x00007ffff563debf in QThreadPrivate::start(void*) (arg=0x555556a15550) at /home/apol/devel/frameworks/qt5/qtbase/src/corelib/thread/qthread_unix.cpp:331
#8  0x00007ffff50c95c2 in start_thread () at /usr/lib/libc.so.6
#9  0x00007ffff514e584 in clone () at /usr/lib/libc.so.6
```

**Comment by RyuzakiKK** [comment]
> I've reproduced it in Discover, issuing an installation of a test app that requires webflow.

Can you please describe more in details what you used to reproduce this error? Were you using `flatpak-sample-authenticator` as describe here https://github.com/flatpak/flatpak/wiki/TestingPurchases or something different?

**Comment by aleixpol** [comment]
More specifically, Discover on this MR.
https://invent.kde.org/plasma/discover/-/merge_requests/272

> Can you please describe more in details what you used to reproduce this error?
I've been testing it using a test repository that one of the flathub developers set up.

> Were you using flatpak-sample-authenticator as describe here https://github.com/flatpak/flatpak/wiki/TestingPurchases or something different?

This seems like it didn't stand the test of time as flatauth.mooo.com:6043 is bouncing.

**Comment by aleixpol** [comment]
>  However to cancel a running webflow you should instead call flatpak_transaction_abort_webflow() with the id that you got in the webflow-start signal.

Correct. That was missing. I've added the call to flatpak_transaction_abort_webflow now. This does not address flatpak_transaction_run not returning though.

**Comment by smcv** [comment]
> > Were you using flatpak-sample-authenticator as describe here https://github.com/flatpak/flatpak/wiki/TestingPurchases or something different?
> 
> This seems like it didn't stand the test of time as flatauth.mooo.com:6043 is bouncing.

The wiki page does say: "Obviously you need to change the base url to wherever you server runs. You also need to tweak the flatpak remote setup to use this uri instead of the old one." So I think the intention is that `flatauth.mooo.com` is just a placeholder, and you should put the address of your `flask-3` server there instead?

(I have no idea how the authentication flow works, sorry.)

**Comment by RyuzakiKK** [comment]
> Correct. That was missing. I've added the call to flatpak_transaction_abort_webflow now. This does not address flatpak_transaction_run not returning though.

I'll try to work out a minimal reproducer to pinpoint what is going wrong.

**Comment by RyuzakiKK** [comment]
@aleixpol As the authenticator are you using https://github.com/flatpak/flatpak-sample-authenticator ?
If that's correct, can you please try to add `data->started_webflow = FALSE;` in the `webflow_cancel()` function https://github.com/flatpak/flatpak-sample-authenticator/blob/master/flatpak-authenticator-webflow.c#L171 and try again?

I [opened an issue about it](https://github.com/flatpak/flatpak-sample-authenticator/issues/1) because apparently the authenticator should not emit the "webflow-done" signal while handling a cancel request.

I tried the setup in https://github.com/flatpak/flatpak/wiki/TestingPurchases (with flath-auth, flat-manager and flatpak-sample-authenticator). Then I made a small change to flatpak cli to let it abort the webflow after a few seconds:

```c
guint test_id = -1;

static void
_test_abort_webflow (GTask *task,
                     gpointer source_object,
                     gpointer data,
                     GCancellable *cancellable)
{
  FlatpakTransaction *transaction = data;
  sleep(10);
  flatpak_transaction_abort_webflow (transaction, test_id);
}

static gboolean
webflow_start (FlatpakTransaction *transaction,
[...]

  g_autoptr(GTask) task = NULL;
  test_id = id;
  task = g_task_new (NULL, NULL, NULL, NULL);
  g_task_set_task_data (task, transaction, NULL);
  g_task_run_in_thread (task, _test_abort_webflow);
```

And the install operation (`flatpak install --user local-test-auth org.gnome.eog`) is cancelled as expected.

I also tried to run your Discover MR, but I'm getting a few errors from kirigami that complains about "loadingplaceholder is not a type" and the webpage is never displayed. I guess that I can't run Discover from git without also getting all its dependencies from git too :/

**Comment by aleixpol** [comment]
It would truly be useful if we had a server where I could test this against. It's hard to be sure it's not my wonky local repository's fault if it doesn't work.
Or at least some container that offered the service? As is I need to have a flat-manager, a populated repository, a flask app running and them all talking to each other...
