### ISSUE TITLE
[Bug]: Debug symbols don't always match associated packages

### ISSUE THREAD

**Issue by Jookia** [flatpak/flatpak#5000]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

22.04

### What architecture are you using?

x86_64

### How to reproduce

1. Install org.freedesktop.Sdk//21.08 (currently 26aed7da8ceb3d067b8af1739d35d1c33c5d80391b964f95a3c2bf000cf6ce49)
2. Install org.freedesktop.Sdk.Debug//21.08 (currently 14eabb3d0442a4c05d12c3c27952d1fe79d6ccd06053e800fcc89428916a2da7)
3. Install a broken application and cause a crash (say com.dosbox_x.DOSBox-X)
4. Use flatpak-coredumpctl to view the crash

### Expected Behavior

I expect GDB to find debug symbols for my associated runtime. Flatpak should find the correct symbols based on the runtime commit I have installed.

### Actual Behavior

Many errors like this:

```
warning: the debug information found in "/usr/lib/debug//usr/lib/x86_64-linux-gnu/libdl-2.33.so.debug" does not match "/usr/lib/x86_64-linux-gnu/libdl.so.2" (CRC mismatch).
warning: the debug information found in "/usr/lib/debug//usr/lib/x86_64-linux-gnu/libdl-2.33.so.debug" does not match "/usr/lib/x86_64-linux-gnu/libdl.so.2" (CRC mismatch).
warning: the debug information found in "/usr/lib/debug//usr/lib/x86_64-linux-gnu/libncurses.so.6.2.debug" does not match "/usr/lib/x86_64-linux-gnu/libncurses.so.6" (CRC mismatch).
warning: the debug information found in "/usr/lib/debug//usr/lib/x86_64-linux-gnu/libncurses.so.6.2.debug" does not match "/usr/lib/x86_64-linux-gnu/libncurses.so.6" (CRC mismatch).
warning: the debug information found in "/usr/lib/debug//usr/lib/x86_64-linux-gnu/libwayland-egl.so.1.20.0.debug" does not match "/usr/lib/x86_64-linux-gnu/libwayland-egl.so.1" (CRC mismatch).
warning: the debug information found in "/usr/lib/debug//usr/lib/x86_64-linux-gnu/libwayland-egl.so.1.20.0.debug" does not match "/usr/lib/x86_64-linux-gnu/libwayland-egl.so.1" (CRC mismatch).
warning: the debug information found in "/usr/lib/debug//usr/lib/x86_64-linux-gnu/libtinfow.so.6.2.debug" does not match "/usr/lib/x86_64-linux-gnu/libtinfow.so.6" (CRC mismatch).
warning: the debug information found in "/usr/lib/debug//usr/lib/x86_64-linux-gnu/libtinfow.so.6.2.debug" does not match "/usr/lib/x86_64-linux-gnu/libtinfow.so.6" (CRC mismatch).
warning: the debug information found in "/usr/lib/debug//usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0.debug" does not match "/usr/lib/x86_64-linux-gnu/libX11-xcb.so.1" (CRC mismatch).
warning: the debug information found in "/usr/lib/debug//usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0.debug" does not match "/usr/lib/x86_64-linux-gnu/libX11-xcb.so.1" (CRC mismatch).
warning: the debug information found in "/usr/lib/debug//usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0.0.0.debug" does not match "/usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0" (CRC mismatch).
warning: the debug information found in "/usr/lib/debug//usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0.0.0.debug" does not match "/usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0" (CRC mismatch).
```

Then an unhelpful stack trace:

```
#0  0x00007ffff7bea53e in _nc_waddch_nosync () from /usr/lib/x86_64-linux-gnu/libncurses.so.6
#1  0x00007ffff7beb5ac in waddnstr () from /usr/lib/x86_64-linux-gnu/libncurses.so.6
#2  0x00007ffff7bf548c in mvwprintw () from /usr/lib/x86_64-linux-gnu/libncurses.so.6
#3  0x000055555573cc51 in DEBUG_RefreshPage (scroll=<optimized out>) at debug_gui.cpp:329
```

**Comment by chrisawi** [comment]
Related: #31
