### ISSUE TITLE
[Bug]: Cannot install and run Onionshare

### ISSUE THREAD

**Issue by heli-aviator** [flatpak/flatpak#5004]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1:1.12.7-1

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

5.18.13-zen1-1-zen

### What architecture are you using?

x86_64

### How to reproduce

1. sudo pacman -Syu
2. sudo pacman -S flatpak
3. flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
4. reboot
5. flatpak install flathub org.onionshare.OnionShare
6. flatpak run org.onionshare.OnionShare

### Expected Behavior

when running: ``` flatpak run org.onionshare.OnionShare ```
I expect onionshare to start

### Actual Behavior

flatpak run org.onionshare.OnionShare   
```                              ─╯
Traceback (most recent call last):
  File "/app/bin/onionshare", line 33, in <module>
    sys.exit(load_entry_point('onionshare==2.5', 'console_scripts', 'onionshare')())
  File "/app/bin/onionshare", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/app/lib/python3.9/site-packages/onionshare-2.5-py3.9.egg/onionshare/__init__.py", line 34, in <module>
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen zipimport>", line 259, in load_module
  File "/app/lib/python3.9/site-packages/onionshare_cli-2.5-py3.9.egg/onionshare_cli/__init__.py", line 30, in <module>
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen zipimport>", line 259, in load_module
  File "/app/lib/python3.9/site-packages/onionshare_cli-2.5-py3.9.egg/onionshare_cli/web/__init__.py", line 21, in <module>
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen zipimport>", line 259, in load_module
  File "/app/lib/python3.9/site-packages/onionshare_cli-2.5-py3.9.egg/onionshare_cli/web/web.py", line 28, in <module>
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/app/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3.9/site-packages/markupsafe/__init__.py)
```

### Additional Information

I have tried this on several distributions including popOS, Manjaro, arco, and my daily driver EndeavourOS. It's the same error on every distribution.

I hope this can get priority to get resolved quickly seeing this is the best way to share documents over the www

**Comment by rusty-snake** [comment]
Duplicate of https://github.com/flathub/org.onionshare.OnionShare/issues/5
Duplicate of https://github.com/flathub/org.onionshare.OnionShare/issues/6

**Comment by mwleeds** [comment]
Closing this under the assumption that it's an issue with that app and not Flatpak itself. If there's reason to believe that's not the case, feel free to re-open.
