### ISSUE TITLE
Crash during flatpak update

### ISSUE THREAD

**Issue by LaurentBonnaud** [flatpak/flatpak#510]
Hi,

I got 2 crashes this morning while I did a routine "flatpak update".
The crash is not reproducible and I could finish the "flatpak update" successfully.
Therefore I could not run flatpak under gdb and all I have is a crash file in /var/crash/ (that goes straight to Canonical and will be ignored there).
So sorry for the incomplete report and the partial backtrace.  Also not all debug info are complete due to missing dbgsym packages.

This is with the latest flatpak version from the PPA:
```
Package: flatpak
Version: 0.8.1-0alexlarsson1~yakkety
```

![screenshot from 2017-01-24 09-43-07](https://cloud.githubusercontent.com/assets/2168323/22240101/d11b4ef4-e219-11e6-9f5a-e2a7a4ac998e.png)

**Comment by alexlarsson** [comment]
Ugh. this is some kind of weird ostree async download crash. 
@cgwalters: Ever seen something like this before?

Next time you update, can you use -v --ostree-verbose? If you can repro the crash with that we'll have a bit more logs about what is happening.

**Comment by LaurentBonnaud** [comment]
No crash today during my daily flatpak update.
This is a very infrequent bug...

**Comment by LaurentBonnaud** [comment]
"flatpak update" crashes occurred again today.  Here is an output with debug options:

```
# flatpak update  -v --ostree-verbose
[...]
XA: Keeping needed object 585e6033d4f989fcfd729fbb73d259013d6bf6d090980065b01ab2f90e706cec.file
XA: Keeping needed object bca957dc965daec7c89e854394fbb2ae35ef1933cb7428fef8eefe22af9d30ff.file
XA: Keeping needed object 96ca954224c7f98388dc142e1201f961b755fcbd87f6679721394110fe989609.file
XA: Keeping needed object d65a555d9529ea4b31256bd62856fca225bef44e52ec52a6cd4c03152bee4d37.file
XA: Pruned 104281/3 objects, size 6,5 kB
Now at 75fe877e4e69.
Updating: org.gnome.Evince/x86_64/stable from gnome-apps
XA: Using cached summary for remote gnome-apps
No updates.
Updating: org.gnome.Evince.Locale/x86_64/stable from gnome-apps
XA: Using cached summary for remote gnome-apps
No updates.
Updating: org.gnome.Games/x86_64/master from gnome-nightly-apps
XA: Using cached summary for remote gnome-nightly-apps

Segmentation fault (core dumped)
```

And here is a partial backtrace that looks exactly like the previous one:

![flatpak-crash](https://cloud.githubusercontent.com/assets/2168323/22616871/1b3bd918-eab7-11e6-907f-af4b7d72dd38.png)

**Comment by LaurentBonnaud** [comment]
Since the crash occurred several times, I got a chance to run flatpak under gdb:

```
# gdb /usr/bin/flatpak 
GNU gdb (Ubuntu 7.12-0ubuntu1) 7.12
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/flatpak...(no debugging symbols found)...done.
(gdb) run update
Starting program: /usr/bin/flatpak update
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Looking for updates...
[New Thread 0x7fffef319700 (LWP 2061)]
[New Thread 0x7fffeeb18700 (LWP 2062)]
[Thread 0x7fffef319700 (LWP 2061) exited]
[New Thread 0x7fffef319700 (LWP 2077)]
[New Thread 0x7fffed244700 (LWP 2078)]
[Thread 0x7fffef319700 (LWP 2077) exited]
[New Thread 0x7fffef319700 (LWP 2083)]
[Thread 0x7fffef319700 (LWP 2083) exited]
[New Thread 0x7fffef319700 (LWP 2088)]
[Thread 0x7fffef319700 (LWP 2088) exited]
[New Thread 0x7fffef319700 (LWP 2093)]
[Thread 0x7fffef319700 (LWP 2093) exited]
[New Thread 0x7fffef319700 (LWP 2098)]
[Thread 0x7fffef319700 (LWP 2098) exited]
[New Thread 0x7fffef319700 (LWP 2103)]
[Thread 0x7fffef319700 (LWP 2103) exited]
[New Thread 0x7fffef319700 (LWP 2108)]
[Thread 0x7fffef319700 (LWP 2108) exited]
[New Thread 0x7fffef319700 (LWP 2113)]
[Thread 0x7fffef319700 (LWP 2113) exited]
[New Thread 0x7fffef319700 (LWP 2118)]
[Thread 0x7fffef319700 (LWP 2118) exited]
Updating: org.gnome.Platform/x86_64/3.20 from gnome
No updates.
Updating: org.gnome.Platform.Locale/x86_64/3.20 from gnome
No updates.
Updating: net.scribus.ScribusDevel/x86_64/master from nightly-graphics
No updates.
Updating: org.darktable.DarktableDevel/x86_64/master from nightly-graphics
No updates.
Updating: org.darktable.DarktableDevel.Locale/x86_64/master from nightly-graphics
No updates.
Updating: org.gimp.GimpDevel/x86_64/master from nightly-graphics
No updates.
Updating: org.gimp.GimpDevel.Locale/x86_64/master from nightly-graphics
No updates.
Updating: org.gnome.Platform/x86_64/master from gnome-nightly
No updates.
Updating: org.gnome.Platform.Locale/x86_64/master from gnome-nightly
No updates.
Updating: org.gnome.Books/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Books.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Calculator/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Calculator.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Calendar/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Calendar.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Epiphany/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Epiphany.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Platform/x86_64/3.22 from gnome
No updates.
Updating: org.gnome.Platform.Locale/x86_64/3.22 from gnome
No updates.
Updating: org.gnome.Epiphany/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Epiphany.Locale/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Evince/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Evince.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Evince/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Evince.Locale/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Games/x86_64/master from gnome-nightly-apps

[New Thread 0x7fffef319700 (LWP 2123)]
[Thread 0x7fffef319700 (LWP 2123) exited]
[New Thread 0x7fffef319700 (LWP 2128)]
[New Thread 0x7fffec524700 (LWP 2137)]
[Thread 0x7fffef319700 (LWP 2128) exited]
1 delta parts, 1 loose fetched; 12 KiB transferred in 1 seconds                                                                   
[Thread 0x7fffec524700 (LWP 2137) exited]
Now at 4bf52fc72143.
Updating: org.gnome.Games.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Glade/x86_64/master from gnome-nightly-apps

[New Thread 0x7fffec524700 (LWP 2152)]
[Thread 0x7fffec524700 (LWP 2152) exited]
[New Thread 0x7fffec524700 (LWP 2157)]
[New Thread 0x7fffef319700 (LWP 2166)]
[Thread 0x7fffec524700 (LWP 2157) exited]
1 delta parts, 1 loose fetched; 974 B transferred in 1 seconds                                                                    
[Thread 0x7fffef319700 (LWP 2166) exited]
Now at 7fd5ab864caa.
Updating: org.gnome.Glade.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Maps/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Maps.Locale/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Nautilus/x86_64/master from gnome-nightly-apps

[New Thread 0x7fffef319700 (LWP 2181)]
[Thread 0x7fffef319700 (LWP 2181) exited]
[New Thread 0x7fffef319700 (LWP 2187)]
[New Thread 0x7fffec524700 (LWP 2195)]
[Thread 0x7fffef319700 (LWP 2187) exited]
2 delta parts, 1 loose fetched; 54 KiB transferred in 2 seconds                                                                   
[Thread 0x7fffec524700 (LWP 2195) exited]
Now at dfc802b12dec.
Updating: org.gnome.Nautilus.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Nautilus/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Nautilus.Locale/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.News/x86_64/master from gnome-nightly-apps

[New Thread 0x7fffec524700 (LWP 2218)]
[Thread 0x7fffec524700 (LWP 2218) exited]
[New Thread 0x7fffec524700 (LWP 2223)]
[New Thread 0x7fffef319700 (LWP 2232)]
[Thread 0x7fffec524700 (LWP 2223) exited]
1 delta parts, 1 loose fetched; 2 KiB transferred in 1 seconds                                                                    
[Thread 0x7fffef319700 (LWP 2232) exited]
Now at d23084f709f9.
Updating: org.gnome.News.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Photos/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Photos.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Photos/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Photos.Locale/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Rhythmbox3/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Rhythmbox3.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Software.XdgApp/x86_64/master from gnome-nightly-apps

[New Thread 0x7fffef319700 (LWP 2249)]
[Thread 0x7fffef319700 (LWP 2249) exited]
[New Thread 0x7fffef319700 (LWP 2254)]
[New Thread 0x7fffec524700 (LWP 2265)]
[Thread 0x7fffef319700 (LWP 2254) exited]
1 delta parts, 1 loose fetched; 150 KiB transferred in 2 seconds                                                                  
[Thread 0x7fffec524700 (LWP 2265) exited]
Now at 3f6e743b2230.
Updating: org.gnome.Software.XdgApp.Locale/x86_64/master from gnome-nightly-apps

[New Thread 0x7fffec524700 (LWP 2280)]
[Thread 0x7fffec524700 (LWP 2280) exited]
[New Thread 0x7fffec524700 (LWP 2285)]
[Thread 0x7fffec524700 (LWP 2285) exited]
5 metadata, 0 content objects fetched; 8 KiB transferred in 1 seconds                                                             
Now at 5ce2fa1c6578.
Updating: org.gnome.Todo/x86_64/master from gnome-nightly-apps

[New Thread 0x7fffec524700 (LWP 2290)]
[Thread 0x7fffec524700 (LWP 2290) exited]
[New Thread 0x7fffec524700 (LWP 2295)]
[New Thread 0x7fffef319700 (LWP 2304)]
[Thread 0x7fffec524700 (LWP 2295) exited]
1 delta parts, 1 loose fetched; 3 KiB transferred in 1 seconds                                                                    
[Thread 0x7fffef319700 (LWP 2304) exited]
Now at 034483c16efe.
Updating: org.gnome.Todo.Locale/x86_64/master from gnome-nightly-apps

[New Thread 0x7fffef319700 (LWP 2320)]
[Thread 0x7fffef319700 (LWP 2320) exited]
[New Thread 0x7fffef319700 (LWP 2325)]
[New Thread 0x7fffec524700 (LWP 2330)]
[Thread 0x7fffef319700 (LWP 2325) exited]
5 metadata, 0 content objects fetched; 6 KiB transferred in 2 seconds                                                             
[Thread 0x7fffec524700 (LWP 2330) exited]
Now at 7ee278534fd5.
Updating: org.gnome.Totem/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Totem.Locale/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.TweakTool/x86_64/master from gnome-nightly-apps

[New Thread 0x7fffec524700 (LWP 2331)]
[Thread 0x7fffec524700 (LWP 2331) exited]
[New Thread 0x7fffec524700 (LWP 2336)]
[New Thread 0x7fffef319700 (LWP 2345)]
[Thread 0x7fffec524700 (LWP 2336) exited]
1 delta parts, 1 loose fetched; 1 KiB transferred in 1 seconds                                                                    
[Thread 0x7fffef319700 (LWP 2345) exited]
Now at d3dd5ac238a2.
Updating: org.gnome.TweakTool.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.Weather/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.Weather.Locale/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.eog/x86_64/master from gnome-nightly-apps

[New Thread 0x7fffef319700 (LWP 2360)]
[Thread 0x7fffef319700 (LWP 2360) exited]
[New Thread 0x7fffef319700 (LWP 2365)]
[New Thread 0x7fffec524700 (LWP 2374)]
[Thread 0x7fffef319700 (LWP 2365) exited]
1 delta parts, 1 loose fetched; 1 KiB transferred in 1 seconds                                                                    
[Thread 0x7fffec524700 (LWP 2374) exited]
Now at 52e60f06c0bb.
Updating: org.gnome.eog.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.eog/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.eog.Locale/x86_64/stable from gnome-apps
No updates.
Updating: org.gnome.frogr/x86_64/master from gnome-nightly-apps

[New Thread 0x7fffec524700 (LWP 2389)]
[Thread 0x7fffec524700 (LWP 2389) exited]
[New Thread 0x7fffec524700 (LWP 2394)]
[New Thread 0x7fffef319700 (LWP 2403)]
[Thread 0x7fffec524700 (LWP 2394) exited]
1 delta parts, 1 loose fetched; 978 B transferred in 1 seconds                                                                    
[Thread 0x7fffef319700 (LWP 2403) exited]
Now at bd56f92d5273.
Updating: org.gnome.frogr.Locale/x86_64/master from gnome-nightly-apps
No updates.
Updating: org.gnome.gedit/x86_64/master from gnome-nightly-apps

[New Thread 0x7fffef319700 (LWP 2418)]
[Thread 0x7fffef319700 (LWP 2418) exited]
[New Thread 0x7fffef319700 (LWP 2423)]
[New Thread 0x7fffec524700 (LWP 2432)]
[Thread 0x7fffef319700 (LWP 2423) exited]
1 delta parts, 1 loose fetched; 7 KiB transferred in 1 seconds                                                                    
[Thread 0x7fffec524700 (LWP 2432) exited]
Now at ae93d5ef19b2.
Updating: org.gnome.gedit.Locale/x86_64/master from gnome-nightly-apps

[New Thread 0x7fffec524700 (LWP 2447)]
[Thread 0x7fffec524700 (LWP 2447) exited]
[New Thread 0x7fffec524700 (LWP 2452)]
[Thread 0x7fffec524700 (LWP 2452) exited]
5 metadata, 0 content objects fetched; 7 KiB transferred in 2 seconds                                                             
Now at 8cda750c81c5.
Updating: org.inkscape.InkscapeDevel/x86_64/master from nightly-graphics
No updates.
Updating: org.inkscape.InkscapeDevel.Locale/x86_64/master from nightly-graphics
No updates.
Updating: org.libreoffice.LibreOffice/x86_64/fresh from org.libreoffice.LibreOffice-origin
No updates.
Updating: org.mozilla.FirefoxDevEdition/x86_64/master from org.mozilla.FirefoxDevEdition-origin

[New Thread 0x7fffec524700 (LWP 2457)]
[Thread 0x7fffec524700 (LWP 2457) exited]
[New Thread 0x7fffec524700 (LWP 2462)]
[New Thread 0x7fffef319700 (LWP 2467)]
[New Thread 0x7fffebd23700 (LWP 2468)]
[New Thread 0x7fffeb522700 (LWP 2469)]
[New Thread 0x7fffead21700 (LWP 2470)]
[New Thread 0x7fffea520700 (LWP 2471)]
[New Thread 0x7fffe9d1f700 (LWP 2472)]
Receiving objects: 95% (20/21) 9,5 MB/s 47,3 MB                                                                                   [Thread 0x7fffebd23700 (LWP 2468) exited]
[Thread 0x7fffef319700 (LWP 2467) exited]
[Thread 0x7fffe9d1f700 (LWP 2472) exited]
[Thread 0x7fffea520700 (LWP 2471) exited]
[Thread 0x7fffead21700 (LWP 2470) exited]
Writing objects: 1                                                                                                                [Thread 0x7fffec524700 (LWP 2462) exited]
9 metadata, 12 content objects fetched; 47963 KiB transferred in 6 seconds                                                        
[Thread 0x7fffed244700 (LWP 2078) exited]
Now at 22f6664b81e7.
Updating: org.mozilla.FirefoxDevEdition.Locale/x86_64/master from org.mozilla.FirefoxDevEdition-origin

[New Thread 0x7fffed244700 (LWP 2488)]
[Thread 0x7fffed244700 (LWP 2488) exited]
[New Thread 0x7fffed244700 (LWP 2493)]
[Thread 0x7fffed244700 (LWP 2493) exited]
3 metadata, 0 content objects fetched; 848 B transferred in 0 seconds                                                             
Now at d8cfa05e6e21.
Updating: org.mypaint.MypaintDevel/x86_64/master from nightly-graphics

[New Thread 0x7fffed244700 (LWP 2502)]
[Thread 0x7fffed244700 (LWP 2502) exited]
[New Thread 0x7fffed244700 (LWP 2507)]
Receiving metadata objects: 5/(estimating) 1,3 kB/s 1,3 kB                                                                        [New Thread 0x7fffec524700 (LWP 2512)]
[Thread 0x7fffed244700 (LWP 2507) exited]
9 metadata, 7 content objects fetched; 38 KiB transferred in 2 seconds                                                            
[Thread 0x7fffec524700 (LWP 2512) exited]
Now at 7b68d8473d1d.
Updating: org.mypaint.MypaintDevel.Locale/x86_64/master from nightly-graphics

[New Thread 0x7fffec524700 (LWP 2527)]
[Thread 0x7fffec524700 (LWP 2527) exited]
[New Thread 0x7fffec524700 (LWP 2532)]
[Thread 0x7fffec524700 (LWP 2532) exited]
5 metadata, 0 content objects fetched; 3 KiB transferred in 1 seconds                                                             
Now at afd7ddb2e09e.
Updating: org.pitivi.Pitivi/x86_64/master from pitivi

[New Thread 0x7fffec524700 (LWP 2537)]

Thread 66 "flatpak" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffec524700 (LWP 2537)]
0x00007ffff6b31025 in g_mutex_lock (mutex=mutex@entry=0x6362363161666139) at ././glib/gthread-posix.c:1336
1336	././glib/gthread-posix.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6b31025 in g_mutex_lock (mutex=mutex@entry=0x6362363161666139) at ././glib/gthread-posix.c:1336
#1  0x00007ffff6ae8b50 in g_source_destroy_internal (source=0x55555658c980, context=0x6362363161666139, have_lock=0)
    at ././glib/gmain.c:1217
#2  0x00007ffff7641088 in  () at /usr/lib/x86_64-linux-gnu/libsoup-2.4.so.1
#3  0x00007ffff6dc9c05 in g_object_unref (_object=0x5555560a9f90) at ././gobject/gobject.c:3148
#4  0x00007ffff7901ce2 in  () at /usr/lib/x86_64-linux-gnu/libostree-1.so.1
#5  0x00007ffff6b13325 in g_thread_proxy (data=0x555555cead40) at ././glib/gthread.c:784
#6  0x00007ffff64416ca in start_thread (arg=0x7fffec524700) at pthread_create.c:333
#7  0x00007ffff617b0af in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
(gdb) 

```

**Comment by LaurentBonnaud** [comment]
I also tried to run "flatpak update" under valgrind, but this time the update finished without crashing.

**Comment by cgwalters** [comment]
Looks like https://github.com/ostreedev/ostree/issues/601 - be sure you have an updated or patched libsoup.

**Comment by LaurentBonnaud** [comment]
Indeed, thanks for finding out!

Here is what is on my system:
```
Package: libsoup2.4-1
Version: 2.56.0-1~ubuntu16.10.1~ppa1
```

It comes from the gnome3-team/gnome3-staging PPA.
In which libsoup version is this bug fixed?

**Comment by matthiasclasen** [comment]
assume this is fixed by now
