### ISSUE TITLE
[Bug]: Flatpak Coredumpctl Crash

### ISSUE THREAD

**Issue by tjapro** [flatpak/flatpak#5244]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.1

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

37

### What architecture are you using?

x86_64

### How to reproduce

1. Run `export GST_DEBUG_FILE="$HOME/gst.log" GST_DEBUG_NO_COLOR=1 WEBKIT_FORCE_SANDBOX=0 G_DEBUG=fatal_criticals`
2. Run `flatpak-coredumpctl re.sonny.Tangram`

### Expected Behavior

The command succedes to open the app in debug mode.

### Actual Behavior

Output a traceback and exit.

### Additional Information

```
flatpak-coredumpctl re.sonny.Tangram

Traceback (most recent call last):
  File "/usr/bin/flatpak-coredumpctl", line 83, in <module>
    coredumper.run()
  File "/usr/bin/flatpak-coredumpctl", line 44, in run
    subprocess.check_call(["coredumpctl", "dump"] + shlex.split(self.coredumpctl_matches),
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['coredumpctl', 'dump']' returned non-zero exit status 1.
```

**Comment by mcatanzaro** [comment]
This script needs better error handling. Shouldn't allow python exceptions to propagate past the top frame: it results in lots of crash reports via distro bug reporter tools. Wouldn't be surprised if most flatpak crash reports from Fedora are actually caused by python exceptions not caught by flatpak-coredumpctl....

**Comment by tjapro** [comment]
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2171299

**Comment by twelho** [comment]
Just hit this as well. `coredumpctl` is present on the host, but not in the Flatpak. The `.Debug` extension and SDK for the Flatpak are both installed.

**Comment by mcatanzaro** [comment]
You should only run coredumpctl on your host system.

**Comment by mcatanzaro** [comment]
Probably fixed by #6649.
