### ISSUE TITLE
[Bug]: `flatpak list` crashes if there is invalid syntax in overrides

### ISSUE THREAD

**Issue by smcv** [flatpak/flatpak#5292]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.2-5-g5b229550

### What Linux distribution are you using?

Debian

### Linux distribution version

12 alpha

### What architecture are you using?

x86_64

### How to reproduce

1. Edit per-app overrides (I used `~/.local/share/flatpak/overrides/org.gnome.Recipes`) and fill in something that is not valid `GKeyFile` syntax
2. `flatpak info org.gnome.Recipes` (or `./_build/app/flatpak info ...` when running uninstalled, etc.)
3. `flatpak run org.gnome.Recipes`
4. `flatpak list`

For example I used this invalid file:

```
[Environment]
x
smcv_flatpak_user_per_app=org.gnome.Recipes
```

where the `x` is invalid.

### Expected Behavior

All commands either succeed with a warning, or fail with an error. No crash.

### Actual Behavior

:+1: `flatpak info org.gnome.Recipes` fails with an error

```
error: Key file contains line “x” which is not a key-value pair, group, or comment
```

:+1: `flatpak run org.gnome.Recipes` fails in the same way

:bomb: `flatpak list` crashes.

```
Thread 1 "flatpak" received signal SIGSEGV, Segmentation fault.
0x000055555560025c in flatpak_deploy_get_deploy_data (deploy=0x0, required_version=4, cancellable=0x0, error=0x0) at ../common/flatpak-dir.c:1477
1477	  return flatpak_load_deploy_data (deploy->dir,
(gdb) bt
#0  0x000055555560025c in flatpak_deploy_get_deploy_data (deploy=0x0, required_version=4, cancellable=0x0, error=0x0)
    at ../common/flatpak-dir.c:1477
#1  0x00005555555b5517 in print_table_for_refs
    (print_apps=1, refs_array=0x55555576e560, arch=0x0, app_runtime=0x0, columns=0x55555576fc40, cancellable=0x0, error=0x7fffffffdbb0)
    at ../app/flatpak-builtins-list.c:175
#2  0x00005555555b644c in print_installed_refs
    (app=1, runtime=1, dirs=0x5555557546e0, arch=0x0, app_runtime=0x0, cols=0x55555576fc40, cancellable=0x0, error=0x7fffffffdbb0)
    at ../app/flatpak-builtins-list.c:379
#3  0x00005555555b669f in flatpak_builtin_list (argc=1, argv=0x7fffffffde48, cancellable=0x0, error=0x7fffffffdbb0)
    at ../app/flatpak-builtins-list.c:424
#4  0x00005555555d740b in flatpak_run (argc=1, argv=0x7fffffffde48, res_error=0x7fffffffdd00) at ../app/flatpak-main.c:859
#5  0x00005555555d7829 in main (argc=2, argv=0x7fffffffde48) at ../app/flatpak-main.c:964
```

**Comment by smcv** [comment]
Duplicate of #5293
