### ISSUE TITLE
[Bug]: `flatpak update` shows `GFileInfo created without standard::size`

### ISSUE THREAD

**Issue by bbhtt** [flatpak/flatpak#5340]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

Flatpak 1.15.3

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

Linux arch 6.2.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 03 Mar 2023 15:58:31 +0000 x86_64 GNU/Linux

### What architecture are you using?

x86_64

### How to reproduce

1. Have some updates (the error doesn't show when there is no update to fetch). I did `flatpak update --commit=<commit id> <app-id>` then `flatpak update`.

2. See the errors:

```
 1. [\] com.transmissionbt.Transmission           stable           u            flathub           365.2 kB / 8.7 MB

Updating… █████████████████▏    86%
(flatpak update:29221): GLib-GIO-CRITICAL **: 07:51:19.310: GFileInfo created without standard::size

(flatpak update:29221): GLib-GIO-CRITICAL **: 07:51:19.310: file ../glib/gio/gfileinfo.c: line 1800 (g_file_info_get_size): should not be reached

(flatpak update:29221): GLib-GIO-CRITICAL **: 07:51:19.311: GFileInfo created without standard::size

(flatpak update:29221): GLib-GIO-CRITICAL **: 07:51:19.311: file ../glib/gio/gfileinfo.c: line 1800 (g_file_info_get_size): should not be reached

(flatpak update:29221): GLib-GIO-CRITICAL **: 07:51:19.311: GFileInfo created without standard::size

(flatpak update:29221): GLib-GIO-CRITICAL **: 07:51:19.311: file ../glib/gio/gfileinfo.c: line 1800 (g_file_info_get_size): should not be reached

(flatpak update:29221): GLib-GIO-CRITICAL **: 07:51:19.311: GFileInfo created without standard::size

(flatpak update:29221): GLib-GIO-CRITICAL **: 07:51:19.311: file ../glib/gio/gfileinfo.c: line 1800 (g_file_info_get_size): should not be reached

(flatpak update:29221): GLib-GIO-CRITICAL **: 07:51:19.312: GFileInfo created without standard::size

(flatpak update:29221): GLib-GIO-CRITICAL **: 07:51:19.312: file ../glib/gio/gfileinfo.c: line 1800 (g_file_info_get_size): should not be reached

(flatpak update:29221): GLib-GIO-CRITICAL **: 07:51:19.312: GFileInfo created without standard::size
```

### Expected Behavior

No error

### Actual Behavior

Shows warnings

### Additional Information

Running with `G_DEBUG=fatal-criticals flatpak update` to make it crash

backtrace:

```
Core was generated by `flatpak update'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007fa8431b0525 in g_logv () from /usr/lib/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7fa827fff6c0 (LWP 28863))]
(gdb) bt
#0  0x00007fa8431b0525 in g_logv () at /usr/lib/libglib-2.0.so.0
#1  0x00007fa8431b07e4 in g_log () at /usr/lib/libglib-2.0.so.0
#2  0x00007fa842fd364d in g_file_info_get_size () at /usr/lib/libgio-2.0.so.0
#3  0x00007fa842d6582f in ostree_raw_file_to_content_stream
    (input=0x0, file_info=0x7fa820001280, xattrs=<optimized out>, out_input=<optimized out>, out_length=0x7fa827ffd918, cancellable=<optimized out>, error=0x7fa827ffeb30) at src/libostree/ostree-core.c:553
#4  0x00007fa842dc1cfa in dispatch_open_splice_and_close
    (error=0x7fa827ffeb30, cancellable=0x0, state=0x7fa827ffd950, repo=0x55b676f365d0)
    at src/libostree/ostree-repo-static-delta-processing.c:585
#5  _ostree_static_delta_part_execute
    (repo=0x55b676f365d0, objects=<optimized out>, part=<optimized out>, stats_only=stats_only@entry=0, stats=stats@entry=0x0, cancellable=0x0, error=0x7fa827ffeb30) at src/libostree/ostree-repo-static-delta-processing.c:237
#6  0x00007fa842dc2056 in static_delta_part_execute_thread
    (task=0x55b6772beed0, object=<optimized out>, datap=<optimized out>, cancellable=<optimized out>)
    at src/libostree/ostree-repo-static-delta-processing.c:312
#7  0x00007fa8430216fc in  () at /usr/lib/libgio-2.0.so.0
#8  0x00007fa8431d7f63 in  () at /usr/lib/libglib-2.0.so.0
#9  0x00007fa8431d57c5 in  () at /usr/lib/libglib-2.0.so.0
#10 0x00007fa84268abb5 in start_thread (arg=<optimized out>) at pthread_create.c:444
#11 0x00007fa84270cd90 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) bt full
#0  0x00007fa8431b0525 in g_logv () at /usr/lib/libglib-2.0.so.0
#1  0x00007fa8431b07e4 in g_log () at /usr/lib/libglib-2.0.so.0
#2  0x00007fa842fd364d in g_file_info_get_size () at /usr/lib/libgio-2.0.so.0
#3  0x00007fa842d6582f in ostree_raw_file_to_content_stream
    (input=0x0, file_info=0x7fa820001280, xattrs=<optimized out>, out_input=<optimized out>, out_length=0x7fa827ffd918, cancellable=<optimized out>, error=0x7fa827ffeb30) at src/libostree/ostree-core.c:553
        file_header = 0x7fa820002190
#4  0x00007fa842dc1cfa in dispatch_open_splice_and_close
    (error=0x7fa827ffeb30, cancellable=0x0, state=0x7fa827ffd950, repo=0x55b676f365d0)
    at src/libostree/ostree-repo-static-delta-processing.c:585
        finfo = 0x7fa820001280
        content_offset = 713583
        objlen = 12884
        object_input = 0x7fa820001200
        memin = 0x0
        ret = 0
        opcode = <optimized out>
        ret = 0
        checksums_data = <optimized out>
        mode_dict = 0x55b6771c4010
        xattr_dict = 0x55b677247da0
        payload = 0x7fa820000c30
        ops = 0x7fa820000eb0
        statedata = {stats_only = 0, repo = 0x55b676f365d0, checksum_index = 55, checksums = 0x55b677222e30 "\002\016\243<\340H\263\025\350\264O\367s\215\372N?\2735\272\3032\223H]\264\236\271\332E\260\276-\002\036\032\207v\037\003dr-\274\035,\236\002\v8ep\340s\303}\200", n_checksums = 61, opdata = 0x7fa83f3fb5aa "", oplen = 35, mode_dict = 0x55b6771c4010, xattr_dict = 0x55b677247da0, object_start = 0, caught_error = 0, async_error = 0x7fa827ffeb30, output_objtype = OSTREE_OBJECT_TYPE_FILE, content_size = 25, checksum = "438966c390c22e06217b4ad1919539fe6d2bd2b740416ab19376b34807dfd4eb", content_out = {initialized = 0, opaque0 = {0x0, 0xffffffff00000022, 0x0, 0x0, 0x100000000, 0x7fa8200011e0, 0x20, 0x0, 0x2134, 0x0}, opaque1 = {0, 0, 33188, 0, 0, 0, 0, 0, 0, 0}}, read_source_object = 0x0, read_source_fd = -1, have_obj = 0, uid = 0, gid = 0, mode = 41471, xattrs = 0x7fa8200022d0, output_target = 0x55b677223548 "C\211fÐ\302.\006!{Jё\2259\376m+ҷ@Aj\261\223v\263H\a\337\324\353\001D\271\036y\006\034٫G\316I\210(\3660\246\337pR\030Z\n\302\373I\264\033\\\024o\361\352\001\274\310h\3448ȱd9\232Dk:\355\271doS\302ے~ը\"^\331m:V\341\311\0019\210\333eE\324u\212\340ZbK\264/\372g\265`lJd\024\326R\355\372\373\--Type <RET> for more, q to quit, c to continue without paging--
247\032|\361\210\001\023W\252\343\270\\\225\3014y\271\300<ߢ\361\2406?d\205\350\237\325i'\371\276\237\306`\177\0010\302\362\033\242\031\327Vi\030\362\032\305l\336\024\023\362\210\327\344\363\273\215\373\243\032\334+\266\3048$", input_target_csum = 0x0, payload_data = 0x7fa83f34d025 "", payload_size = 713698}
        state = 0x7fa827ffd950
        n_executed = 59
#5  _ostree_static_delta_part_execute
    (repo=0x55b676f365d0, objects=<optimized out>, part=<optimized out>, stats_only=stats_only@entry=0, stats=stats@entry=0x0, cancellable=0x0, error=0x7fa827ffeb30) at src/libostree/ostree-repo-static-delta-processing.c:237
        opcode = <optimized out>
        ret = 0
        checksums_data = <optimized out>
        mode_dict = 0x55b6771c4010
        xattr_dict = 0x55b677247da0
        payload = 0x7fa820000c30
        ops = 0x7fa820000eb0
        statedata = {stats_only = 0, repo = 0x55b676f365d0, checksum_index = 55, checksums = 0x55b677222e30 "\002\016\243<\340H\263\025\350\264O\367s\215\372N?\2735\272\3032\223H]\264\236\271\332E\260\276-\002\036\032\207v\037\003dr-\274\035,\236\002\v8ep\340s\303}\200", n_checksums = 61, opdata = 0x7fa83f3fb5aa "", oplen = 35, mode_dict = 0x55b6771c4010, xattr_dict = 0x55b677247da0, object_start = 0, caught_error = 0, async_error = 0x7fa827ffeb30, output_objtype = OSTREE_OBJECT_TYPE_FILE, content_size = 25, checksum = "438966c390c22e06217b4ad1919539fe6d2bd2b740416ab19376b34807dfd4eb", content_out = {initialized = 0, opaque0 = {0x0, 0xffffffff00000022, 0x0, 0x0, 0x100000000, 0x7fa8200011e0, 0x20, 0x0, 0x2134, 0x0}, opaque1 = {0, 0, 33188, 0, 0, 0, 0, 0, 0, 0}}, read_source_object = 0x0, read_source_fd = -1, have_obj = 0, uid = 0, gid = 0, mode = 41471, xattrs = 0x7fa8200022d0, output_target = 0x55b677223548 "C\211fÐ\302.\006!{Jё\2259\376m+ҷ@Aj\261\223v\263H\a\337\324\353\001D\271\036y\006\034٫G\316I\210(\3660\246\337pR\030Z\n\302\373I\264\033\\\024o\361\352\001\274\310h\3448ȱd9\232Dk:\355\271doS\302ے~ը\"^\331m:V\341\311\0019\210\333eE\324u\212\340ZbK\264/\372g\265`lJd\024\326R\355\372\373\247\032|\361\210\001\023W\252\343\270\\\225\3014y\271\300<ߢ\361\2406?d\205\350\237\325i'\371\276\237\306`\177\0010\302\362\033\242\031\327Vi\030\362\032\305l\336\024\023\362\210\327\344\363\273\215\373\243\032\334+\266\3048$", input_target_csum = 0x0, payload_data = 0x7fa83f34d025 "", payload_size = 713698}
        state = 0x7fa827ffd950
        n_executed = 59
#6  0x00007fa842dc2056 in static_delta_part_execute_thread
    (task=0x55b6772beed0, object=<optimized out>, datap=<optimized out>, cancellable=<optimized out>)
    at src/libostree/ostree-repo-static-delta-processing.c:312
--Type <RET> for more, q to quit, c to continue without paging--
        error = 0x0
        data = <optimized out>
#7  0x00007fa8430216fc in  () at /usr/lib/libgio-2.0.so.0
#8  0x00007fa8431d7f63 in  () at /usr/lib/libglib-2.0.so.0
#9  0x00007fa8431d57c5 in  () at /usr/lib/libglib-2.0.so.0
#10 0x00007fa84268abb5 in start_thread (arg=<optimized out>) at pthread_create.c:444
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140360645388528, 3981314454654716372, -280, 0, 140360583997648, 140360193929216, -4030660537182156332, -4030443806746572332}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#11 0x00007fa84270cd90 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

`glib2 2.75.4-1`

**Comment by smcv** [comment]
This looks like a bug in libostree (which Flatpak uses) rather than a bug in Flatpak itself, and there is probably no change to Flatpak that would avoid these warnings.

I've opened https://github.com/ostreedev/ostree/issues/2827. Please follow up there with details of the version of libostree that you are using.

**Comment by themanyone** [comment]
Fond memories.
`GLib-GIO-CRITICAL ... GFileInfo created without standard::is-backup`
 still pops up on older gtk2 apps. It goes away when they are recompiled for gtk3.

**Comment by smcv** [comment]
> `GLib-GIO-CRITICAL ... GFileInfo created without standard::is-backup` still pops up on older gtk2 apps

I'm sure it does, but this is a GTK2 bug, not a Flatpak bug, and there is no change to Flatpak that can fix it.

If this is a problem for you, please ask your GTK2 vendor to backport https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/5645 to GTK2. For example Debian did this in <https://salsa.debian.org/gnome-team/gtk2/-/blob/debian/latest/debian/patches/Check-for-attribute-availability-before-accessing-it.patch?ref_type=heads>.

Issues that are not caused by Flatpak are not on-topic for Flatpak's issue tracker.
