### ISSUE TITLE
[Bug]: Flatpak not mounting /tmp/.X11-unix or /run/flatpak/Xauthority

### ISSUE THREAD

**Issue by RilicTheFox** [flatpak/flatpak#5487]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.4

### What Linux distribution are you using?

Fedora Silverblue

### Linux distribution version

6.4.4-200.fc38.x86_64

### What architecture are you using?

x86_64

### Expected Behavior

Flatpak apps launched by other flatpak apps using `flatpak-spawn --host /bin/sh -c 'flatpak run app.name.here'` should launch and find the $DISPLAY variable.

### Actual Behavior

No $DISPLAY variable is found and the app cannot launch.

### Additional Information

I have a log of an application being launched that shows that the folders listed in the title aren't being mounted: https://paste.gg/p/anonymous/5a5abb90e9034e3d8d3b21cc02f4f4fe

It happens to QT, GTK, Electron, SDL, and more.

Here it what a program running into this issue looks like in the logs (ran from BlackBox terminal, which is a flatpak'd terminal with the same problem):

```
[rilic@phoenix ~]$ flatpak run hu.kramo.Cartridges 
(process:2): Gdk-WARNING **: 14:27:15.786: No such backend: *
Traceback (most recent call last):
  File "/app/bin/cartridges", line 58, in <module>
    from src import main
  File "/app/share/cartridges/src/main.py", line 33, in <module>
    from src import shared
  File "/app/share/cartridges/src/shared.py", line 47, in <module>
    monitor.get_scale_factor() for monitor in Gdk.Display.get_default().get_monitors()
AttributeError: 'NoneType' object has no attribute 'get_monitors'

[rilic@phoenix ~]$ flatpak run org.gnome.Loupe 
(loupe:2): Gtk-WARNING **: 14:27:17.269: Failed to open display

[rilic@phoenix ~]$ flatpak run com.discordapp.Discord 
Disabling updates already done
Discord 0.0.28
[5:0725/142719.299950:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
[5:0725/142719.299979:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.
[0725/142719.307510:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
/app/bin/discord: line 24:     5 Aborted                 (core dumped) env TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/discord/Discord $FLAGS "$@"

[rilic@phoenix ~]$ flatpak run org.prismlauncher.PrismLauncher 
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```
Cartridges (a game launcher that supports flatpak games) and Gnome Builder also have the same issue, with apps spawned by them erroring in the exact same way.

**Comment by chrisawi** [comment]
Is this still happening? Is this an X11 session?

The presence of "Allowing x11 access" rules out a `fallback-x11` issue and points toward `DISPLAY` being unset in the host shell.

**Comment by GittyMac** [comment]
This seems to still happen with `flatpak-spawn` and QT apps. Spawning a QT app like Krita or Prism Launcher gives this error. 
```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, xcb.
```
Trying to use args on the host Flatpak side and the spawn side to change the platform does not seem to change it either. GTK apps work perfectly fine however.
