### ISSUE TITLE
[Build error]: Build failed because of DNS timeout

### ISSUE THREAD

**Issue by daviddavo** [flatpak/flatpak#5513]
The build [7889](https://buildbot.flathub.org/#/builders/33/builds/7889) failed with the following error.

```
✔ Running packaging hooks
  ✔ Running generateAssets hook
  ✔ Running prePackage hook
❯ Packaging application
  ❯ Packaging for x64 on linux
    ✖ Copying files
      › getaddrinfo EAI_AGAIN github.com
    ◼ Preparing native dependencies
    ◼ Finalizing package
◼ Running postPackage hook
An unhandled rejection has occurred inside Forge:
RequestError: getaddrinfo EAI_AGAIN github.com
at ClientRequest.<anonymous> (/run/build/logseq/logseq/static/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:526:35)
    at ClientRequest.emit (node:domain:489:12)
    at origin.emit (/run/build/logseq/logseq/static/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)
[?25h[?25h
error Command failed with exit code 1.
```

It this a flatpak issue? buildbot? configuration?

**Comment by hfiguiere** [comment]
I'm gonna go on a whim, given that this is the wrong tracker, that you are trying to access the network during a flathub build.

Thing is flathub build run sandbox without network access. So you must make sure that the build works offline.

This behave as expected for `flatpak-builder` (different repo) and `flathub` (another repo.
