### ISSUE TITLE
[Bug]: Crash in flatpak_dir_get_default_locales() since 14c54830

### ISSUE THREAD

**Issue by smcv** [flatpak/flatpak#5588]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.4-90-gba86840f8

### What Linux distribution are you using?

Debian

### Linux distribution version

unstable

### What architecture are you using?

x86_64

### How to reproduce

`meson test` on my laptop fails with a segmentation fault. `${builddir}/app/flatpak update` is enough to reproduce it.

### Expected Behavior

No crash

### Actual Behavior

```
Thread 1 "flatpak" received signal SIGSEGV, Segmentation fault.
0x0000555555604e26 in flatpak_dir_get_default_locale_languages (self=self@entry=0x555555726a30)
    at ../../../../src/flatpak/common/flatpak-dir.c:16475
16475	  return sort_strv (flatpak_strv_merge (extra_languages, (char **) langs->pdata));
(gdb) bt
#0  0x0000555555604e26 in flatpak_dir_get_default_locale_languages (self=self@entry=0x555555726a30)
    at ../../../../src/flatpak/common/flatpak-dir.c:16475
#1  0x0000555555605040 in flatpak_dir_get_locale_languages (self=0x555555726a30)
    at ../../../../src/flatpak/common/flatpak-dir.c:16508
#2  flatpak_dir_get_locale_subpaths (self=0x555555726a30) at ../../../../src/flatpak/common/flatpak-dir.c:16514
#3  0x00005555556363c8 in flatpak_transaction_add_ref
    (self=self@entry=0x555555726800, remote=0x55555582c0e0 "flathub", 
    remote@entry=0x0, ref=ref@entry=0x555555816500, subpaths=subpaths@entry=0x0, previous_ids=previous_ids@entry=0x0, commit=commit@entry=0x0, kind=FLATPAK_TRANSACTION_OPERATION_UPDATE, bundle=0x0, external_metadata=0x0, pin_on_deploy=0, out_op=0x0, error=0x7fffffffda18) at ../../../../src/flatpak/common/flatpak-transaction.c:2687
#4  0x000055555563adc2 in flatpak_transaction_add_update
    (self=self@entry=0x555555726800, ref=<optimized out>, subpaths=subpaths@entry=0x0, commit=commit@entry=0x0, error=error@entry=0x7fffffffda18) at ../../../../src/flatpak/common/flatpak-transaction.c:3061
#5  0x00005555555bb6ce in flatpak_builtin_update
    (argc=<optimized out>, argv=<optimized out>, cancellable=<optimized out>, error=0x7fffffffda18)
    at ../../../../src/flatpak/app/flatpak-builtins-update.c:209
#6  0x000055555557f833 in flatpak_run (res_error=0x7fffffffda08, argv=<optimized out>, argc=<optimized out>)
    at ../../../../src/flatpak/app/flatpak-main.c:859
#7  main (argc=<optimized out>, argv=<optimized out>) at ../../../../src/flatpak/app/flatpak-main.c:964
``

### Additional Information

_No response_

**Comment by smcv** [comment]
This is a regression in #5018, and is a release blocker for 1.15.x. cc @GeorgesStavracas @hadess
