### ISSUE TITLE
[Bug]: flatpak-portal crash (also: infinite loop) in child_watch_died due to unsafe concurrent access to GHashTable

### ISSUE THREAD

**Issue by mcatanzaro** [flatpak/flatpak#5605]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.4-4.fc39

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

39

### What architecture are you using?

x86_64

### How to reproduce

Unknown

### Expected Behavior

No crash

### Actual Behavior

I found this flatpak-portal crash in coredumpctl:

```
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
    at pthread_kill.c:44
#1  0x00007f26eacc78a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007f26eac758ee in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f26eac5d8ff in __GI_abort () at abort.c:79
#4  0x00007f26eb6db056 in g_assertion_message
    (domain=domain@entry=0x7f26eb7790be "GLib", file=file@entry=0x7f26eb77dc5c "../glib/ghash.c", line=line@entry=552, func=func@entry=0x7f26eb77efe0 <__func__.25.lto_priv.3> "g_hash_table_remove_node", message=message@entry=0x7f26d0002090 "assertion failed: (hash_table->nnodes > 0)") at ../glib/gtestutils.c:3497
#5  0x00007f26eb73cdc7 in g_assertion_message_expr
    (domain=0x7f26eb7790be "GLib", file=0x7f26eb77dc5c "../glib/ghash.c", line=552, func=0x7f26eb77efe0 <__func__.25.lto_priv.3> "g_hash_table_remove_node", expr=<optimized out>) at ../glib/gtestutils.c:3523
#6  0x00007f26eb6fd837 in g_hash_table_remove_node
    (hash_table=hash_table@entry=0x55d5c43e6520, i=i@entry=4, notify=notify@entry=1) at ../glib/ghash.c:552
#7  0x00007f26eb701809 in g_hash_table_remove_internal (notify=1, key=0x3a62, hash_table=0x55d5c43e6520)
    at ../glib/ghash.c:1776
#8  g_hash_table_remove (hash_table=0x55d5c43e6520, key=0x3a62) at ../glib/ghash.c:1804
#9  0x000055d5c2d574e4 in child_watch_died (pid=<optimized out>, status=0, user_data=0x7f26c407b2c0)
    at ../portal/flatpak-portal.c:240
#10 0x00007f26eb717b32 in g_child_watch_dispatch
    (source=0x7f26c407b2f0, callback=0x55d5c2d57450 <child_watch_died>, user_data=0x7f26c407b2c0)
    at ../glib/gmain.c:5989
#11 0x00007f26eb716e5c in g_main_dispatch (context=0x55d5c43f1f10) at ../glib/gmain.c:3476
#12 g_main_context_dispatch_unlocked (context=0x55d5c43f1f10) at ../glib/gmain.c:4284
#13 0x00007f26eb771dd8 in g_main_context_iterate_unlocked.isra.0
    (context=0x55d5c43f1f10, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../glib/gmain.c:4349
#14 0x00007f26eb718447 in g_main_loop_run (loop=0x55d5c4415550) at ../glib/gmain.c:4551
#15 0x000055d5c2d4ea33 in main (argc=<optimized out>, argv=<optimized out>) at ../portal/flatpak-portal.c:3084
```

It's crashing on this assertion: `assertion failed: (hash_table->nnodes > 0)`

Let's print the hash table:

```
(gdb) print *client_pid_data_hash
$2 = {size = 8, mod = 7, mask = 7, nnodes = 0, noccupied = 3, have_big_keys = 0, have_big_values = 1, 
  keys = 0x55d5c440ce80, hashes = 0x55d5c440b550, values = 0x7f26c4049dc0, 
  hash_func = 0x7f26eb6f86d0 <g_direct_hash>, key_equal_func = 0x0, ref_count = 1, version = 146, 
  key_destroy_func = 0x0, value_destroy_func = 0x55d5c2d4f5a0 <pid_data_free>}
```

So the hash table is empty (`nnodes = 0`, the 3 occupied nodes are tombstones where data used to be, and the `size = 8` indicates capacity rather than contents), and trying to remove from an empty hash table is wrong.

### Additional Information

Full backtrace [gdb.txt](https://github.com/flatpak/flatpak/files/13490779/gdb.txt)

**Comment by smcv** [comment]
> trying to remove from an empty hash table is wrong

Really? My understanding was that `g_hash_table_remove()` will remove an item whose key matches the given one if it exists, but is not (meant to be) a programming error to call when there is no such item.

**Comment by smcv** [comment]
My reading of the assertion failure is that if we reach that assertion, somehow `g_hash_table_remove_internal()` has called `g_hash_table_lookup_node()` and successfully found an item, but then on entering `g_hash_table_remove_node()`, it turns out that `nnodes == 0`, which is an inconsistency: if that's the case, then `g_hash_table_lookup_node()` should have failed.

**Comment by A6GibKm** [comment]
On debian 12 I been running into an issue where flatpak-portal would use most of my 12 cores. When attaching to the process I see

```
g_hash_table_lookup_node (hash_return=<synthetic pointer>, key=0x53431, hash_table=0x6187ed4c75e0) at ../../../glib/ghash.c:512
512	../../../glib/ghash.c: No such file or directory.
(gdb) bt
#0  g_hash_table_lookup_node (hash_return=<synthetic pointer>, key=0x53431, hash_table=0x6187ed4c75e0) at ../../../glib/ghash.c:512
#1  g_hash_table_remove_internal (notify=1, key=0x53431, hash_table=0x6187ed4c75e0) at ../../../glib/ghash.c:1769
#2  g_hash_table_remove (hash_table=0x6187ed4c75e0, key=0x53431) at ../../../glib/ghash.c:1802
#3  0x00006187e19e4ab3 in child_watch_died (pid=<error reading variable: value has been optimized out>, status=34304, status@entry=<error reading variable: value has been optimized out>, user_data=0x76f4bc007950, 
    user_data@entry=<error reading variable: value has been optimized out>) at portal/flatpak-portal.c:241
#4  0x000076f73e176864 in g_child_watch_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at ../../../glib/gmain.c:5840
#5  0x000076f73e17a67f in g_main_dispatch (context=0x6187ed4ff9d0) at ../../../glib/gmain.c:3454
#6  g_main_context_dispatch (context=context@entry=0x6187ed4ff9d0) at ../../../glib/gmain.c:4172
#7  0x000076f73e17aa38 in g_main_context_iterate (context=0x6187ed4ff9d0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4248
#8  0x000076f73e17acef in g_main_loop_run (loop=0x6187ed52e1f0) at ../../../glib/gmain.c:4448
#9  0x00006187e19e3290 in main (argc=<optimized out>, argv=<optimized out>) at portal/flatpak-portal.c:3104
```

Is this the same issue?

**Comment by pwithnall** [comment]
Nice detective work

**Comment by mcatanzaro** [comment]
> This entire file will need to be audited.

Well, all the global state at the top needs to be audited:

```
static GStrv original_environ = NULL;
static GHashTable *client_pid_data_hash = NULL;
static GDBusConnection *session_bus = NULL;
static GNetworkMonitor *network_monitor = NULL;
static gboolean no_idle_exit = FALSE;
static guint name_owner_id = 0;
static GMainLoop *main_loop;
static PortalFlatpak *portal;
static gboolean opt_verbose;
static int opt_poll_timeout;
static gboolean opt_poll_when_metered;
static FlatpakSpawnSupportFlags supports = 0;
```

And also:

```
static XdpDbusPermissionStore *permission_store;
```

Unfortunately this file does a huge amount of work in threads, so it will be easy to mess up. Locking requirements must be documented carefully.

**Comment by matthiasclasen** [comment]
> Well, all the global state at the top needs to be audited:

Looking through that list,

> static GDBusConnection *session_bus = NULL;

This is threadsafe

>  static GNetworkMonitor *network_monitor = NULL;

This is only used on the main thread

> static GMainLoop *main_loop;

Is threadsafe

> static XdpDbusPermissionStore *permission_store;

This is a GDbusProxy and thus, also threadsafe

So Georges MR should be enough.
