### ISSUE TITLE
[Bug]:  Memory on Flatpak remove or update

### ISSUE THREAD

**Issue by hfiguiere** [flatpak/flatpak#5856]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.8~git

### What Linux distribution are you using?

Fedora Silverblue

### Linux distribution version

39

### What architecture are you using?

x86_64

### How to reproduce

You need flatpak built with address sanitizer.

1. flatpak remove SOME_APP
or
2. flatpak update SOME_APP

### Expected Behavior

ASan says nothing.

### Actual Behavior

```
=================================================================
==248507==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f7184ad92ef in malloc (/lib64/libasan.so.8+0xd92ef) (BuildId: 2b657470ea196ba4342e3bd8a3cc138b1e200599)
    #1 0x7f7184917619 in g_malloc (/lib64/libglib-2.0.so.0+0x61619) (BuildId: b6cf99186f67796c572114f06c6ee38c300c212b)
    #2 0x7f7184933244 in g_slice_alloc (/lib64/libglib-2.0.so.0+0x7d244) (BuildId: b6cf99186f67796c572114f06c6ee38c300c212b)
    #3 0x7f7184958936 in g_variant_new_from_children (/lib64/libglib-2.0.so.0+0xa2936) (BuildId: b6cf99186f67796c572114f06c6ee38c300c212b)
    #4 0x7f7184958a38 in g_variant_builder_end (/lib64/libglib-2.0.so.0+0xa2a38) (BuildId: b6cf99186f67796c572114f06c6ee38c300c212b)
    #5 0x7f7184959b9a in g_variant_valist_new (/lib64/libglib-2.0.so.0+0xa3b9a) (BuildId: b6cf99186f67796c572114f06c6ee38c300c212b)
    #6 0x7f718495a13f in g_variant_new_va (/lib64/libglib-2.0.so.0+0xa413f) (BuildId: b6cf99186f67796c572114f06c6ee38c300c212b)
    #7 0x7f718495a277 in g_variant_new (/lib64/libglib-2.0.so.0+0xa4277) (BuildId: b6cf99186f67796c572114f06c6ee38c300c212b)
    #8 0x7f71847ef55d in decode_method_reply (/lib64/libgio-2.0.so.0+0x10f55d) (BuildId: dff065bc34450814b3a7c8099363b39625066515)
    #9 0x7f71847eff74 in g_dbus_connection_call_sync_internal (/lib64/libgio-2.0.so.0+0x10ff74) (BuildId: dff065bc34450814b3a7c8099363b39625066515)
    #10 0x7f71847f02f5 in g_dbus_connection_call_sync (/lib64/libgio-2.0.so.0+0x1102f5) (BuildId: dff065bc34450814b3a7c8099363b39625066515)
    #11 0x58245f in maybe_reload_dbus_config ../common/flatpak-dir.c:7072
    #12 0x582693 in flatpak_dir_run_triggers ../common/flatpak-dir.c:7097
    #13 0x67349b in flatpak_transaction_real_run ../common/flatpak-transaction.c:5329
    #14 0x4e044f in flatpak_cli_transaction_run ../app/flatpak-cli-transaction.c:1673
    #15 0x66e8d6 in flatpak_transaction_run ../common/flatpak-transaction.c:4737
    #16 0x4d049f in flatpak_builtin_uninstall ../app/flatpak-builtins-uninstall.c:538
    #17 0x4ea999 in flatpak_run ../app/flatpak-main.c:857
    #18 0x4eb3da in main ../app/flatpak-main.c:962
    #19 0x7f7183dc6149 in __libc_start_call_main (/lib64/libc.so.6+0x28149) (BuildId: 7ea8d85df0e89b90c63ac7ed2b3578b2e7728756)
    #20 0x7f7183dc620a in __libc_start_main_impl (/lib64/libc.so.6+0x2820a) (BuildId: 7ea8d85df0e89b90c63ac7ed2b3578b2e7728756)
    #21 0x41a9d4 in _start (/var/home/hub/source/flatpak/_build/app/flatpak+0x41a9d4) (BuildId: 5c29e80ea4124090b680e53423586f35d2d98036)

SUMMARY: AddressSanitizer: 64 byte(s) leaked in 1 allocation(s).
```

Update
```
=================================================================
==259925==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7ff5d1cd92ef in malloc (/lib64/libasan.so.8+0xd92ef) (BuildId: 2b657470ea196ba4342e3bd8a3cc138b1e200599)
    #1 0x7ff5d1b17619 in g_malloc (/lib64/libglib-2.0.so.0+0x61619) (BuildId: b6cf99186f67796c572114f06c6ee38c300c212b)
    #2 0x7ff5d1b33244 in g_slice_alloc (/lib64/libglib-2.0.so.0+0x7d244) (BuildId: b6cf99186f67796c572114f06c6ee38c300c212b)
    #3 0x7ff5d1b58936 in g_variant_new_from_children (/lib64/libglib-2.0.so.0+0xa2936) (BuildId: b6cf99186f67796c572114f06c6ee38c300c212b)
    #4 0x7ff5d1b58a38 in g_variant_builder_end (/lib64/libglib-2.0.so.0+0xa2a38) (BuildId: b6cf99186f67796c572114f06c6ee38c300c212b)
    #5 0x7ff5d1b59b9a in g_variant_valist_new (/lib64/libglib-2.0.so.0+0xa3b9a) (BuildId: b6cf99186f67796c572114f06c6ee38c300c212b)
    #6 0x7ff5d1b5a13f in g_variant_new_va (/lib64/libglib-2.0.so.0+0xa413f) (BuildId: b6cf99186f67796c572114f06c6ee38c300c212b)
    #7 0x7ff5d1b5a277 in g_variant_new (/lib64/libglib-2.0.so.0+0xa4277) (BuildId: b6cf99186f67796c572114f06c6ee38c300c212b)
    #8 0x7ff5d19ef55d in decode_method_reply (/lib64/libgio-2.0.so.0+0x10f55d) (BuildId: dff065bc34450814b3a7c8099363b39625066515)
    #9 0x7ff5d19eff74 in g_dbus_connection_call_sync_internal (/lib64/libgio-2.0.so.0+0x10ff74) (BuildId: dff065bc34450814b3a7c8099363b39625066515)
    #10 0x7ff5d19f02f5 in g_dbus_connection_call_sync (/lib64/libgio-2.0.so.0+0x1102f5) (BuildId: dff065bc34450814b3a7c8099363b39625066515)
    #11 0x58245f in maybe_reload_dbus_config ../common/flatpak-dir.c:7072
    #12 0x582693 in flatpak_dir_run_triggers ../common/flatpak-dir.c:7097
    #13 0x67349b in flatpak_transaction_real_run ../common/flatpak-transaction.c:5329
    #14 0x4e044f in flatpak_cli_transaction_run ../app/flatpak-cli-transaction.c:1673
    #15 0x66e8d6 in flatpak_transaction_run ../common/flatpak-transaction.c:4737
    #16 0x4d2667 in flatpak_builtin_update ../app/flatpak-builtins-update.c:259
    #17 0x4ea999 in flatpak_run ../app/flatpak-main.c:857
    #18 0x4eb3da in main ../app/flatpak-main.c:962
    #19 0x7ff5d0ffb149 in __libc_start_call_main (/lib64/libc.so.6+0x28149) (BuildId: 7ea8d85df0e89b90c63ac7ed2b3578b2e7728756)
    #20 0x7ff5d0ffb20a in __libc_start_main_impl (/lib64/libc.so.6+0x2820a) (BuildId: 7ea8d85df0e89b90c63ac7ed2b3578b2e7728756)
    #21 0x41a9d4 in _start (/var/home/hub/source/flatpak/_build/app/flatpak+0x41a9d4) (BuildId: 5c29e80ea4124090b680e53423586f35d2d98036)

SUMMARY: AddressSanitizer: 64 byte(s) leaked in 1 allocation(s).
```

### Additional Information

The leak might actually be in glib.

```
Name        : glib2
Version     : 2.78.3
Release     : 1.fc39
```

**Comment by swick** [comment]
Just a stupid bug, not checking the return value: https://github.com/flatpak/flatpak/pull/5858

**Comment by hfiguiere** [comment]
Isn't there a "must use return value" warning in gcc? This would save a lot of trouble.

**Comment by smcv** [comment]
> Isn't there a "must use return value" warning in gcc?

There is, but to catch this issue, it would need to have been added to the declaration of `g_dbus_connection_call_sync()` (and probably hundreds of other functions) in GLib, which is not a directly actionable change for Flatpak.
