### ISSUE TITLE
Flatpak stuck extremely long sometimes after all done when updating

### ISSUE THREAD

**Issue by cclvi256** [flatpak/flatpak#5857]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.8

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

Fedora 40 KDE Spin

### What architecture are you using?

x86_64

### How to reproduce

1. Install some packages which is old.
2. Update them, then the flatpak will be stuck for extremely long time, if you interrupt it with `Ctrl + C`, the stuck can occur again when running `flatpak update` again.

### Expected Behavior

Flatpak quit after all done.

### Actual Behavior

It had been being stuck there for a extremely long time, until my `Ctrl + C` or rebooting.

**Comment by cclvi256** [comment]
Someone told me that try `flatpak repair`, this does not work at once, but after several rebootings, flatpak works well now.

**Comment by Rudxain** [comment]
Same issue: Debian 13 "Trixie", Flatpak 1.16.0

It gets stuck "Installing" even after the progress says "7/7". It can't be `kill`ed with signals, only forcefully. CPU 100%. This implies there's an infinite loop somewhere

**Comment by aursulis** [comment]
Seemingly same issue here with Flatpak 1.16.0 and Fedora 42 KDE edition. I attached gdb to the flatpak process (running `flatpak update`) while in this waiting state and dumped all threads:

```
(gdb) info threads
  Id   Target Id                                          Frame 
* 1    Thread 0x7f6d149d14c0 (LWP 3979) "flatpak"         __syscall_cancel_arch () at ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S:56
  2    Thread 0x7f6d049fb6c0 (LWP 4025) "dconf worker"    __syscall_cancel_arch () at ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S:56
  3    Thread 0x7f6d051fc6c0 (LWP 3985) "polkit agent li" __syscall_cancel_arch () at ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S:56
  4    Thread 0x7f6d059fd6c0 (LWP 3984) "gdbus"           __syscall_cancel_arch () at ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S:56
  5    Thread 0x7f6d061fe6c0 (LWP 3983) "gmain"           __syscall_cancel_arch () at ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S:56
  6    Thread 0x7f6d069ff6c0 (LWP 3982) "pool-spawner"    syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
(gdb) bt
#0  __syscall_cancel_arch () at ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S:56
#1  0x00007f6d15a0072a in __internal_syscall_cancel (a1=<optimized out>, a2=<optimized out>, a3=<optimized out>, a4=a4@entry=0, a5=a5@entry=0, a6=a6@entry=0, nr=7) at cancellation.c:49
#2  0x00007f6d15a00774 in __syscall_cancel (a1=<optimized out>, a2=<optimized out>, a3=<optimized out>, a4=a4@entry=0, a5=a5@entry=0, a6=a6@entry=0, nr=7) at cancellation.c:75
#3  0x00007f6d15a79a0e in __GI___poll (fds=<optimized out>, nfds=<optimized out>, timeout=<optimized out>) at ../sysdeps/unix/sysv/linux/poll.c:29
#4  0x00007f6d15e867e9 in poll (__fds=0x7ffe52ac3140, __nfds=<optimized out>, __timeout=<optimized out>) at /usr/include/bits/poll2.h:44
#5  Curl_poll (ufds=0x7ffe52ac3140, nfds=<optimized out>, timeout_ms=<optimized out>) at ../../lib/select.c:313
#6  0x00007f6d15e7b00e in multi_wait.part.0.lto_priv.0 (multi=0x56146b02cb00, extra_fds=0x0, extra_nfds=0, timeout_ms=798, ret=0x0, extrawait=true, use_wakeup=true) at ../../lib/multi.c:1366
#7  0x00007f6d15e73612 in multi_wait (multi=<optimized out>, extra_fds=<optimized out>, extra_nfds=<optimized out>, timeout_ms=<optimized out>, ret=<optimized out>, extrawait=true, use_wakeup=true) at ../../lib/multi.c:1508
#8  curl_multi_poll (multi=<optimized out>, extra_fds=<optimized out>, extra_nfds=<optimized out>, timeout_ms=<optimized out>, ret=<optimized out>) at ../../lib/multi.c:1509
#9  0x00007f6d15e48ad5 in easy_transfer (multi=<optimized out>) at ../../lib/easy.c:698
#10 easy_perform (events=false, data=0x56146a91a930) at ../../lib/easy.c:796
#11 curl_easy_perform (data=0x56146a91a930) at ../../lib/easy.c:815
#12 0x0000561459cae98c in flatpak_download_http_uri_once (session=session@entry=0x56146a984160, data=data@entry=0x7ffe52ac4550, uri=uri@entry=0x56146a8edc50 "https://registry.fedoraproject.org/index/static?label%3Aorg.flatpak.ref%3Aexists=1&architecture=amd64&os=linux&tag=latest", error=error@entry=0x7ffe52ac34b0)
    at ../common/flatpak-utils-http.c:528
#13 0x0000561459cb005b in flatpak_cache_http_uri.constprop.0 (http_session=0x56146a984160, uri=<optimized out>, flags=<optimized out>, dest_dfd=<optimized out>, dest_subpath=<optimized out>, cancellable=<optimized out>, error=0x7ffe52ac86e0, user_data=<optimized out>, progress=<optimized out>)
    at ../common/flatpak-utils-http.c:1461
#14 0x0000561459c4963f in flatpak_oci_index_ensure_cached (http_session=0x56146a984160, uri=<optimized out>, index=0x56146a6b9d60, index_uri_out=0x7ffe52ac8850, cancellable=0x0, error=0x7ffe52ac86d8) at ../common/flatpak-oci-registry.c:2847
#15 flatpak_dir_update_oci_index (self=<optimized out>, remote=<optimized out>, index_uri_out=0x7ffe52ac8850, cancellable=0x0, error=0x7ffe52ac8830) at ../common/flatpak-dir.c:5099
#16 0x0000561459c662a1 in flatpak_dir_remote_make_oci_summary (self=0x56146a6c7a90, remote=0x56146a8d0e60 "fedora", only_cached=0, out_summary=0x7ffe52ac8840, cancellable=0x0, error=0x7ffe52ac8830) at ../common/flatpak-dir.c:11982
#17 flatpak_dir_remote_fetch_summary (self=0x56146a6c7a90, name_or_uri=0x56146a8d0e60 "fedora", only_cached=0, out_summary=0x7ffe52ac8820, out_summary_sig=0x7ffe52ac8828, cancellable=0x0, error=0x7ffe52ac8830) at ../common/flatpak-dir.c:12336
#18 _flatpak_dir_get_remote_state.constprop.0 (self=0x56146a6c7a90, remote_or_uri=0x56146a8d0e60 "fedora", optional=1, local_only=<optimized out>, only_cached=0, cancellable=0x0, error=0x7ffe52ac8af0, opt_summary_sig=0x0, opt_summary=0x0, opt_summary_is_index=0) at ../common/flatpak-dir.c:12911
#19 0x0000561459c4fe07 in flatpak_dir_get_remote_state_optional (self=0x56146a6c7a90, remote=0x56146a8d0e60 "fedora", only_cached=0, cancellable=<optimized out>, error=<optimized out>) at ../common/flatpak-dir.c:13075
#20 flatpak_dir_update_appstream.constprop.0 (self=0x56146a6c7a90, remote=0x56146a8d0e60 "fedora", arch=0x561459cd185b "x86_64", out_changed=0x7ffe52ac8aec, cancellable=0x0, error=0x7ffe52ac8af0, progress=0x0) at ../common/flatpak-dir.c:5266
#21 0x0000561459c26322 in update_appstream (dirs=0x56146a6d0050, remote=<optimized out>, arch=0x561459cd185b "x86_64", ttl=86400, quiet=1, cancellable=0x0, error=0x7ffe52ac8c78) at ../app/flatpak-builtins-utils.c:697
#22 0x0000561459c18f0e in flatpak_builtin_update (argc=<optimized out>, argv=<optimized out>, cancellable=0x0, error=0x7ffe52ac8c78) at ../app/flatpak-builtins-update.c:279
#23 0x0000561459bd14c0 in flatpak_run (argc=<optimized out>, argv=<optimized out>, res_error=0x7ffe52ac8c68) at ../app/flatpak-main.c:859
#24 main (argc=<optimized out>, argv=<optimized out>) at ../app/flatpak-main.c:964
(gdb) t 2
[Switching to thread 2 (Thread 0x7f6d049fb6c0 (LWP 4025))]
#0  __syscall_cancel_arch () at ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S:56
56              ret
(gdb) bt
#0  __syscall_cancel_arch () at ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S:56
#1  0x00007f6d15a0072a in __internal_syscall_cancel (a1=<optimized out>, a2=<optimized out>, a3=<optimized out>, a4=<optimized out>, a5=a5@entry=8, a6=a6@entry=0, nr=271) at cancellation.c:49
#2  0x00007f6d15a00774 in __syscall_cancel (a1=<optimized out>, a2=<optimized out>, a3=<optimized out>, a4=<optimized out>, a5=a5@entry=8, a6=a6@entry=0, nr=271) at cancellation.c:75
#3  0x00007f6d15a79f36 in __GI_ppoll (fds=fds@entry=0x7f6cf0004d80, nfds=nfds@entry=1, timeout=<optimized out>, timeout@entry=0x0, sigmask=sigmask@entry=0x0) at ../sysdeps/unix/sysv/linux/ppoll.c:42
#4  0x00007f6d1658e210 in ppoll (__fds=0x7f6cf0004d80, __nfds=1, __timeout=0x0, __ss=0x0) at /usr/include/bits/poll2.h:101
#5  g_main_context_poll_unlocked (priority=<optimized out>, context=0x56146a6e06f0, timeout_usec=<optimized out>, fds=0x7f6cf0004d80, n_fds=1) at ../glib/gmain.c:4632
#6  g_main_context_iterate_unlocked (context=context@entry=0x56146a6e06f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4309
#7  0x00007f6d1658e2d3 in g_main_context_iteration (context=context@entry=0x56146a6e06f0, may_block=may_block@entry=1) at ../glib/gmain.c:4379
#8  0x00007f6d1499bb1d in dconf_gdbus_worker_thread (user_data=0x56146a6e06f0) at ../gdbus/dconf-gdbus-thread.c:82
#9  0x00007f6d165bb8e2 in g_thread_proxy (data=0x56146a8fac70) at ../glib/gthread.c:893
#10 0x00007f6d15a03f14 in start_thread (arg=<optimized out>) at pthread_create.c:448
#11 0x00007f6d15a86aac in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
(gdb) t 3
[Switching to thread 3 (Thread 0x7f6d051fc6c0 (LWP 3985))]
#0  __syscall_cancel_arch () at ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S:56
56              ret
(gdb) bt
#0  __syscall_cancel_arch () at ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S:56
#1  0x00007f6d15a0072a in __internal_syscall_cancel (a1=<optimized out>, a2=<optimized out>, a3=<optimized out>, a4=<optimized out>, a5=a5@entry=8, a6=a6@entry=0, nr=271) at cancellation.c:49
#2  0x00007f6d15a00774 in __syscall_cancel (a1=<optimized out>, a2=<optimized out>, a3=<optimized out>, a4=<optimized out>, a5=a5@entry=8, a6=a6@entry=0, nr=271) at cancellation.c:75
#3  0x00007f6d15a79f36 in __GI_ppoll (fds=fds@entry=0x7f6cfc001630, nfds=nfds@entry=1, timeout=<optimized out>, timeout@entry=0x0, sigmask=sigmask@entry=0x0) at ../sysdeps/unix/sysv/linux/ppoll.c:42
#4  0x00007f6d1658e210 in ppoll (__fds=0x7f6cfc001630, __nfds=1, __timeout=0x0, __ss=0x0) at /usr/include/bits/poll2.h:101
#5  g_main_context_poll_unlocked (priority=<optimized out>, context=0x7f6cfc000b70, timeout_usec=<optimized out>, fds=0x7f6cfc001630, n_fds=1) at ../glib/gmain.c:4632
#6  g_main_context_iterate_unlocked (context=0x7f6cfc000b70, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4309
#7  0x00007f6d1658e3cf in g_main_loop_run (loop=0x7f6cfc000db0) at ../glib/gmain.c:4516
#8  0x00007f6d15ff8e7f in server_thread_func (user_data=0x56146a6be500) at ../src/polkitagent/polkitagentlistener.c:357
#9  0x00007f6d165bb8e2 in g_thread_proxy (data=0x56146a6c6110) at ../glib/gthread.c:893
#10 0x00007f6d15a03f14 in start_thread (arg=<optimized out>) at pthread_create.c:448
#11 0x00007f6d15a86aac in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
(gdb) t 4
[Switching to thread 4 (Thread 0x7f6d059fd6c0 (LWP 3984))]
#0  __syscall_cancel_arch () at ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S:56
56              ret
(gdb) bt
#0  __syscall_cancel_arch () at ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S:56
#1  0x00007f6d15a0072a in __internal_syscall_cancel (a1=<optimized out>, a2=<optimized out>, a3=<optimized out>, a4=<optimized out>, a5=a5@entry=8, a6=a6@entry=0, nr=271) at cancellation.c:49
#2  0x00007f6d15a00774 in __syscall_cancel (a1=<optimized out>, a2=<optimized out>, a3=<optimized out>, a4=<optimized out>, a5=a5@entry=8, a6=a6@entry=0, nr=271) at cancellation.c:75
#3  0x00007f6d15a79f36 in __GI_ppoll (fds=fds@entry=0x7f6cf8000bb0, nfds=nfds@entry=3, timeout=<optimized out>, timeout@entry=0x0, sigmask=sigmask@entry=0x0) at ../sysdeps/unix/sysv/linux/ppoll.c:42
#4  0x00007f6d1658e210 in ppoll (__fds=0x7f6cf8000bb0, __nfds=3, __timeout=0x0, __ss=0x0) at /usr/include/bits/poll2.h:101
#5  g_main_context_poll_unlocked (priority=<optimized out>, context=0x56146a6bead0, timeout_usec=<optimized out>, fds=0x7f6cf8000bb0, n_fds=3) at ../glib/gmain.c:4632
#6  g_main_context_iterate_unlocked (context=0x56146a6bead0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4309
#7  0x00007f6d1658e3cf in g_main_loop_run (loop=0x56146a6bece0) at ../glib/gmain.c:4516
#8  0x00007f6d1645c2b2 in gdbus_shared_thread_func (user_data=0x56146a6c0b30) at ../gio/gdbusprivate.c:284
#9  0x00007f6d165bb8e2 in g_thread_proxy (data=0x56146a6bed00) at ../glib/gthread.c:893
#10 0x00007f6d15a03f14 in start_thread (arg=<optimized out>) at pthread_create.c:448
#11 0x00007f6d15a86aac in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
(gdb) t 5
[Switching to thread 5 (Thread 0x7f6d061fe6c0 (LWP 3983))]
#0  __syscall_cancel_arch () at ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S:56
56              ret
(gdb) bt
#0  __syscall_cancel_arch () at ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S:56
#1  0x00007f6d15a0072a in __internal_syscall_cancel (a1=<optimized out>, a2=<optimized out>, a3=<optimized out>, a4=<optimized out>, a5=a5@entry=8, a6=a6@entry=0, nr=271) at cancellation.c:49
#2  0x00007f6d15a00774 in __syscall_cancel (a1=<optimized out>, a2=<optimized out>, a3=<optimized out>, a4=<optimized out>, a5=a5@entry=8, a6=a6@entry=0, nr=271) at cancellation.c:75
#3  0x00007f6d15a79f36 in __GI_ppoll (fds=fds@entry=0x7f6d00000b70, nfds=nfds@entry=1, timeout=<optimized out>, timeout@entry=0x0, sigmask=sigmask@entry=0x0) at ../sysdeps/unix/sysv/linux/ppoll.c:42
#4  0x00007f6d1658e210 in ppoll (__fds=0x7f6d00000b70, __nfds=1, __timeout=0x0, __ss=0x0) at /usr/include/bits/poll2.h:101
#5  g_main_context_poll_unlocked (priority=<optimized out>, context=0x56146a6b2240, timeout_usec=<optimized out>, fds=0x7f6d00000b70, n_fds=1) at ../glib/gmain.c:4632
#6  g_main_context_iterate_unlocked (context=context@entry=0x56146a6b2240, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4309
#7  0x00007f6d1658e2d3 in g_main_context_iteration (context=0x56146a6b2240, may_block=may_block@entry=1) at ../glib/gmain.c:4379
#8  0x00007f6d1658e321 in glib_worker_main (data=<optimized out>) at ../glib/gmain.c:6578
#9  0x00007f6d165bb8e2 in g_thread_proxy (data=0x56146a6b2460) at ../glib/gthread.c:893
#10 0x00007f6d15a03f14 in start_thread (arg=<optimized out>) at pthread_create.c:448
#11 0x00007f6d15a86aac in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
(gdb) t 6
[Switching to thread 6 (Thread 0x7f6d069ff6c0 (LWP 3982))]
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
38              cmpq $-4095, %rax       /* Check %rax for error.  */
(gdb) bt
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f6d165b13ed in g_cond_wait_impl (cond=0x56146a6b00a8, mutex=0x56146a6b00a0) at ../glib/gthread-posix.c:1026
#2  g_cond_wait (cond=0x56146a6b00a8, mutex=0x56146a6b00a0) at ../glib/gthread.c:1686
#3  0x00007f6d1654de2c in g_async_queue_pop_intern_unlocked (queue=0x56146a6b00a0, wait=1, end_time=-1) at ../glib/gasyncqueue.c:375
#4  0x00007f6d165bbd94 in g_thread_pool_spawn_thread (data=<optimized out>) at ../glib/gthreadpool.c:297
#5  0x00007f6d165bb8e2 in g_thread_proxy (data=0x56146a6b1f20) at ../glib/gthread.c:893
#6  0x00007f6d15a03f14 in start_thread (arg=<optimized out>) at pthread_create.c:448
#7  0x00007f6d15a86aac in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

```

**Comment by swick** [comment]
Can this be reproduced consistently? What repo is the update coming from?
