### ISSUE TITLE
[Bug]:  Memory leak on update

### ISSUE THREAD

**Issue by hfiguiere** [flatpak/flatpak#5883]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.9-7-g9cdf7e5f

### What Linux distribution are you using?

Fedora Silverblue

### What architecture are you using?

x86_64

### How to reproduce

1. use flaptak built with asan
2. `flatpak update org.gnome.Builder.Devel com.github.flxzt.rnote org.gnome.Fractal`

Not even it's one of the specific package but here is what was update:
```
 1. [✓] com.github.flxzt.rnote.Locale                     stable                       u              flathub                    19.0 kB / 406.4 kB
 2. [✓] org.freedesktop.Platform.GL.default               24.08beta                    u              gnome-nightly             123.6 MB / 154.2 MB
 3. [✓] org.freedesktop.Platform.GL.default               24.08beta-extra              u              gnome-nightly              18.5 MB / 154.3 MB
 4. [✓] org.freedesktop.Platform.VAAPI.Intel              24.08beta                    u              gnome-nightly              13.5 MB / 13.5 MB
 5. [✓] org.freedesktop.Platform.openh264                 2.4.1beta                    u              gnome-nightly             637.7 kB / 977.2 kB
 6. [✓] org.gnome.Builder.Devel.Locale                    master                       u              gnome-nightly              10.5 kB / 3.5 MB
 7. [✓] org.gnome.Fractal.Locale                          stable                       u              flathub                    37.2 kB / 700.7 kB
 8. [✓] org.gnome.Fractal                                 stable                       u              flathub                    21.6 MB / 26.3 MB
 9. [✓] com.github.flxzt.rnote                            stable                       u              flathub                     7.6 MB / 20.5 MB
10. [✓] org.gnome.Sdk.Locale                              master                       u              gnome-nightly             542.4 kB / 392.3 MB
11. [✓] org.gnome.Sdk                                     master                       u              gnome-nightly             578.3 MB / 756.5 MB
12. [✓] org.gnome.Builder.Devel                           master                       u              gnome-nightly              13.2 MB / 147.7 MB
```

### Expected Behavior

asan report no leak

### Actual Behavior

asen report leaks. See below:

### Additional Information

```
=================================================================
==460496==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 35 byte(s) in 1 object(s) allocated from:
    #0 0x7f0ee5352997 in malloc (/lib64/libasan.so.8+0xf7997) (BuildId: f3e12225ec68aeb6b252b128640495c94a4600f3)
    #1 0x7f0ee5170879 in g_malloc (/lib64/libglib-2.0.so.0+0x63879) (BuildId: 36b60dbd02e796145a982d0151ce37202ec05649)
    #2 0x7f0ee518a272 in g_memdup2 (/lib64/libglib-2.0.so.0+0x7d272) (BuildId: 36b60dbd02e796145a982d0151ce37202ec05649)
    #3 0x7f0ee51b8ad6 in g_variant_valist_get (/lib64/libglib-2.0.so.0+0xabad6) (BuildId: 36b60dbd02e796145a982d0151ce37202ec05649)
    #4 0x7f0ee51b85f7 in g_variant_valist_get (/lib64/libglib-2.0.so.0+0xab5f7) (BuildId: 36b60dbd02e796145a982d0151ce37202ec05649)
    #5 0x7f0ee51b8b4f in g_variant_get_va (/lib64/libglib-2.0.so.0+0xabb4f) (BuildId: 36b60dbd02e796145a982d0151ce37202ec05649)
    #6 0x7f0ee51b9ae8 in g_variant_get_child (/lib64/libglib-2.0.so.0+0xacae8) (BuildId: 36b60dbd02e796145a982d0151ce37202ec05649)
    #7 0x648d71 in flatpak_repo_parse_extra_data_sources ../common/flatpak-repo-utils.c:377
    #8 0x5782c8 in flatpak_dir_pull_extra_data ../common/flatpak-dir.c:5719
    #9 0x57bab1 in flatpak_dir_pull ../common/flatpak-dir.c:6146
    #10 0x59e824 in flatpak_dir_update ../common/flatpak-dir.c:10639
    #11 0x6a462e in _run_op_kind ../common/flatpak-transaction.c:4842
    #12 0x6a7820 in flatpak_transaction_real_run ../common/flatpak-transaction.c:5277
    #13 0x4e097a in flatpak_cli_transaction_run ../app/flatpak-cli-transaction.c:1673
    #14 0x6a32a4 in flatpak_transaction_run ../common/flatpak-transaction.c:4738
    #15 0x4d2b10 in flatpak_builtin_update ../app/flatpak-builtins-update.c:259
    #16 0x4eaef9 in flatpak_run ../app/flatpak-main.c:857
    #17 0x4eb940 in main ../app/flatpak-main.c:962
    #18 0x7f0ee45f3087 in __libc_start_call_main (/lib64/libc.so.6+0x2a087) (BuildId: 980b86754dc53e7fd5473d38c629977f47aafd2f)
    #19 0x7f0ee45f314a in __libc_start_main_alias_2 (/lib64/libc.so.6+0x2a14a) (BuildId: 980b86754dc53e7fd5473d38c629977f47aafd2f)
    #20 0x41aa14 in _start (/var/home/hub/source/flatpak/_build/app/flatpak+0x41aa14) (BuildId: fd8842208daf5bd6641eb4225655150e8519ef99)

SUMMARY: AddressSanitizer: 35 byte(s) leaked in 1 allocation(s).
```

**Comment by swick** [comment]
I think this should fix it but reproducing requires something with extra data
```patch
diff --git ./common/flatpak-repo-utils.c ../common/flatpak-repo-utils.c
index 26652f1f..ab31f880 100644
--- ./common/flatpak-repo-utils.c
+++ ../common/flatpak-repo-utils.c
@@ -374,7 +374,7 @@ flatpak_repo_parse_extra_data_sources (GVariant      *extra_data_sources,
                                        const char   **uri)
 {
   g_autoptr(GVariant) sha256_v = NULL;
-  g_variant_get_child (extra_data_sources, index, "(^aytt@ay&s)",
+  g_variant_get_child (extra_data_sources, index, "(^&aytt@ay&s)",
                        name,
                        download_size,
                        installed_size,
```
