### ISSUE TITLE
[Bug]: `flatpak install --include-sdk --user` segfaults if the SDK is already installed system-wide

### ISSUE THREAD

**Issue by theCapypara** [flatpak/flatpak#5894]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.6

### What Linux distribution are you using?

NixOS

### Linux distribution version

24.05

### What architecture are you using?

x86_64

### How to reproduce

1. Run `flatpak install --include-sdk org.skytemple.SkyTemple --user`
2. (Select Flathub if asked for multiple remote)

### Expected Behavior

I get shown a summary of what will be installed and can install the package

### Actual Behavior

The CLI segfaults.

### Additional Information

GDB backtrace:
```
#0  0x00000000004c7a6b in flatpak_transaction_real_run ()
#1  0x000000000044df17 in flatpak_cli_transaction_run ()
#2  0x0000000000424d42 in flatpak_builtin_install ()
#3  0x000000000041b72a in main ()
```

**Comment by bbhtt** [comment]
```
#0  0x0000561eef396c67 in add_deps (self=<optimized out>, op=0x561f08be5440, error=<optimized out>) at ../common/flatpak-transaction.c:2598
2598              if (sdk_op->kind != FLATPAK_TRANSACTION_OPERATION_UNINSTALL)                                                                                               
[Current thread is 1 (Thread 0x7fa533bb5940 (LWP 105534))]
(gdb) bt
#0  0x0000561eef396c67 in add_deps (self=<optimized out>, op=0x561f08be5440 [FlatpakTransactionOperation], error=<optimized out>) at ../common/flatpak-transaction.c:2598
#1  flatpak_transaction_real_run (self=0x561f08cd32e0 [FlatpakCliTransaction], cancellable=0x0, error=0x7ffca337fb88) at ../common/flatpak-transaction.c:5177
#2  0x0000561eef33d143 in flatpak_cli_transaction_run (transaction=0x561f08cd32e0 [FlatpakCliTransaction], cancellable=<optimized out>, error=0x7ffca337fb88)
    at ../app/flatpak-cli-transaction.c:1625
#3  0x0000561eef31acc9 in flatpak_transaction_run (transaction=0x561f08cd32e0 [FlatpakCliTransaction], cancellable=0x0, error=0x7ffca337fb88)
    at ../common/flatpak-transaction.c:4737
#4  flatpak_builtin_install (argc=<optimized out>, argv=<optimized out>, cancellable=0x0, error=0x7ffca337fb88) at ../app/flatpak-builtins-install.c:593
#5  0x0000561eef2f3e64 in flatpak_run (argc=<optimized out>, argv=<optimized out>, res_error=0x7ffca337fb78) at ../app/flatpak-main.c:857
#6  main (argc=<optimized out>, argv=<optimized out>) at ../app/flatpak-main.c:962
```

The crash seems to only happen, when the target SDK to install is already installed in `system` location, but `flatpak install --include-sdk` is being run as `--user`.
