### ISSUE TITLE
[Bug]: Running any Flatpak app results in Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by shyuen** [flatpak/flatpak#6039]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

Flatpak 1.14.10

### What Linux distribution are you using?

NixOS

### Linux distribution version

Linux nixos 6.6.64 #1-NixOS SMP PREEMPT_DYNAMIC Mon Dec  9 09:33:11 UTC 2024 x86_64 GNU/Linux

### What architecture are you using?

x86_64

### How to reproduce

1. Running any flatpak application from the desktop UI (KDE) results in the icon appearing in the taskbar for a few seconds before disappearing. Some applications will trigger a KDE notification (Portal) that  X application is running in the background. 

2. Attempting to run the application from the terminal results in the `Segmentation fault (core dumped)` message. For example: 
```
flatpak run com.github.tchx84.Flatseal
Segmentation fault (core dumped)

flatpak run com.valvesoftware.Steam
Segmentation fault (core dumped)
```

----

I was able to use `flatpak-coredumpctl` to help troubleshoot. At first I was getting the following output:
```
flatpak-coredumpctl io.freetubeapp.FreeTube
Executable /nix/store/kfmql08inbrz0b6lmz5nbjpkfgzaprjk-OpenTabletDriver-0.6.4.0-unstable-2024-11-25/lib/OpenTabletDriver/OpenTabletDriver.Daemon doesn't seem to be a flatpaked application.
Running: `"flatpak" "run" "--filesystem=home" "--filesystem=/tmp" "--command=gdb" "--devel" "io.freetubeapp.FreeTube" "/nix/store/kfmql08inbrz0b6lmz5nbjpkfgzaprjk-OpenTabletDriver-0.6.4.0-unstable-2024-11-25/lib/OpenTabletDriver/OpenTabletDriver.Daemon" "/tmp/tmpetbyuxju"`
error: runtime/org.freedesktop.Sdk/x86_64/23.08 not installed
Traceback (most recent call last):
  File "/nix/store/2qk3ywzivihsh12xv11lz0jv9b3b14ib-flatpak-1.14.10/bin/.flatpak-coredumpctl-wrapped", line 83, in <module>
    coredumper.run()
  File "/nix/store/2qk3ywzivihsh12xv11lz0jv9b3b14ib-flatpak-1.14.10/bin/.flatpak-coredumpctl-wrapped", line 58, in run
    subprocess.check_call(flatpak_command)
  File "/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['flatpak', 'run', '--filesystem=home', '--filesystem=/tmp', '--command=gdb', '--devel', 'io.freetubeapp.FreeTube', '/nix/store/kfmql08inbrz0b6lmz5nbjpkfgzaprjk-OpenTabletDriver-0.6.4.0-unstable-2024-11-25/lib/OpenTabletDriver/OpenTabletDriver.Daemon', '/tmp/tmpetbyuxju']' returned non-zero exit status 1
```
After some searching, I was able to figure out that I was missing `org.freedesktop.Sdk` from the error line. I was able to install the missing sdk with `flatpak install flathub org.freedesktop.Sdk`. 

However, now I'm getting the following core dump message:
```
flatpak-coredumpctl io.freetubeapp.FreeTube
Executable /nix/store/2qk3ywzivihsh12xv11lz0jv9b3b14ib-flatpak-1.14.10/bin/.flatpak-wrapped doesn't seem to be a flatpaked application.
Running: `"flatpak" "run" "--filesystem=home" "--filesystem=/tmp" "--command=gdb" "--devel" "io.freetubeapp.FreeTube" "/nix/store/2qk3ywzivihsh12xv11lz0jv9b3b14ib-flatpak-1.14.10/bin/.flatpak-wrapped" "/tmp/tmpaeiywcak"`
Traceback (most recent call last):
  File "/nix/store/2qk3ywzivihsh12xv11lz0jv9b3b14ib-flatpak-1.14.10/bin/.flatpak-coredumpctl-wrapped", line 83, in <module>
    coredumper.run()
  File "/nix/store/2qk3ywzivihsh12xv11lz0jv9b3b14ib-flatpak-1.14.10/bin/.flatpak-coredumpctl-wrapped", line 58, in run
    subprocess.check_call(flatpak_command)
  File "/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['flatpak', 'run', '--filesystem=home', '--filesystem=/tmp', '--command=gdb', '--devel', 'io.freetubeapp.FreeTube', '/nix/store/2qk3ywzivihsh12xv11lz0jv9b3b14ib-flatpak-1.14.10/bin/.flatpak-wrapped', '/tmp/tmpaeiywcak']' died with <Signals.SIGSEGV: 11>.

```

I'm not too sure how to proceed from here and any help would be appreciated. Thanks

### Expected Behavior

Applications should start up and run.

### Actual Behavior

Applications crash silently from desktop or output a `Segmentation fault (core dumped)` when run from terminal. 

### Additional Information

I think this is more of a troubleshooting issue more than a bug. I believe Flatpak got into a bad state on this particular machine. Another computer that also uses NixOS flatpaks doesn't encounter this issue. 

I have tried the following to no avail:
1.  Do a `flatpak repair` 
2. `mv` or delete the `~/.local/share/flatpak` 
3. Uninstall flatpak by removing `services.flatpak.enable = true` and rebuilding, doing a `sudo nix-collect-garbage -d` to  clean it out, and doing another `nixos-rebuild` to add flatpak back in.

**Comment by smcv** [comment]
> I was able to use `flatpak-coredumpctl` to help troubleshoot

`flatpak-coredumpctl` is only helpful if the crashing process is something inside the Flatpak sandbox. It seems that in your case, it is Flatpak itself that is crashing, before it has been able to create the sandbox.

Please contact NixOS's support channels to find out what distro-specific steps are needed to get a backtrace from a crashing program (what you're looking for is the NixOS equivalent of https://wiki.debian.org/HowToGetABacktrace in Debian or https://wiki.archlinux.org/title/Debugging/Getting_traces in Arch).

**Comment by shyuen** [comment]
Closing this issue. 

Origin of the problem appears to be with way the Nix packages for Flatpaks and Sweethome 3d interact to cause segfault the interaction. 

Related information:
https://discourse.nixos.org/t/installing-sweethome3d-makes-flatpak-run-segfault/48177
