### ISSUE TITLE
Failed to update org.gnome.Platform : Server returned status 503

### ISSUE THREAD

**Issue by suhas2go** [flatpak/flatpak#608]
I'm getting the following error when I'm trying to update my development environment. I'm not sure if this is an entirely server problem.
```
$ ptvenv --update
Updating org.gnome.Platform
Looking for updates...
Updating: org.gnome.Platform/x86_64/3.22 from gnome

Receiving metadata objects: 555/(estimating) 106.2 kB/s 7.0 MB                                                                                        
Error: Failed to update org.gnome.Platform/x86_64/3.22: While pulling runtime/org.gnome.Platform/x86_64/3.22 from remote gnome: Server returned status 503: Service Unavailable
Updating: org.gnome.Platform.Locale/x86_64/3.22 from gnome

Receiving objects: 4940% (247/5) 441 bytes/s 14.1 kB                                                                                                  **
OSTree:ERROR:src/libostree/ostree-repo-pull.c:927:meta_fetch_on_complete: assertion failed: (pull_data->n_outstanding_metadata_fetches > 0)
Traceback (most recent call last):
  File "/home/drogon/Documents/Projs/pitivi-dev4/pitivi/build/flatpak/pitivi-flatpak", line 659, in <module>
    app_flatpak.run()
  File "/home/drogon/Documents/Projs/pitivi-dev4/pitivi/build/flatpak/pitivi-flatpak", line 445, in run
    self.update_all()
  File "/home/drogon/Documents/Projs/pitivi-dev4/pitivi/build/flatpak/pitivi-flatpak", line 595, in update_all
    m.update()
  File "/home/drogon/Documents/Projs/pitivi-dev4/pitivi/build/flatpak/pitivi-flatpak", line 322, in update
    comment="Updating %s" % self.name)
  File "/home/drogon/Documents/Projs/pitivi-dev4/pitivi/build/flatpak/pitivi-flatpak", line 146, in flatpak
    return subprocess.check_call(command)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['flatpak', 'update', '--user', 'org.gnome.Platform', '3.22']' returned non-zero exit status -6
```

**Comment by alexlarsson** [comment]
This seems to be caused by logrotate temporarily pausing httpd.
This works now though, right?

**Comment by aleb** [comment]
For how long is it paused?

**Comment by alexlarsson** [comment]
Unclear. Its just as SIGHUP to reload the config

**Comment by suhas2go** [comment]
@alexlarsson I'm still getting the error. I'll try again sometime later.

**Comment by aleb** [comment]
How can we find out what URL is fetched when this request fails?

**Comment by aleb** [comment]
Printing which URL failed to download would help in other cases also, see for example: https://github.com/pitivi/pitivi/issues/154

**Comment by alexlarsson** [comment]
It would have to be done in ostree itself, but yeah if we report e.g. a 403, we should probably also report the uri.
Ping @cgwalters.

**Comment by cgwalters** [comment]
We do log more information to the journal, but yeah, we can add the URI to the error messages too

**Comment by matthiasclasen** [comment]
seems like an ostree issue
